// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.4
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="conv,hls_ip_2015_4,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020clg484-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=8.750000,HLS_SYN_LAT=-1,HLS_SYN_TPT=-1,HLS_SYN_MEM=3,HLS_SYN_DSP=9,HLS_SYN_FF=1858,HLS_SYN_LUT=2340}" *)

module conv (
        s_axi_AXILiteS_AWVALID,
        s_axi_AXILiteS_AWREADY,
        s_axi_AXILiteS_AWADDR,
        s_axi_AXILiteS_WVALID,
        s_axi_AXILiteS_WREADY,
        s_axi_AXILiteS_WDATA,
        s_axi_AXILiteS_WSTRB,
        s_axi_AXILiteS_ARVALID,
        s_axi_AXILiteS_ARREADY,
        s_axi_AXILiteS_ARADDR,
        s_axi_AXILiteS_RVALID,
        s_axi_AXILiteS_RREADY,
        s_axi_AXILiteS_RDATA,
        s_axi_AXILiteS_RRESP,
        s_axi_AXILiteS_BVALID,
        s_axi_AXILiteS_BREADY,
        s_axi_AXILiteS_BRESP,
        ap_clk,
        ap_rst_n,
        interrupt,
        m_axi_CRTL_BUS_AWVALID,
        m_axi_CRTL_BUS_AWREADY,
        m_axi_CRTL_BUS_AWADDR,
        m_axi_CRTL_BUS_AWID,
        m_axi_CRTL_BUS_AWLEN,
        m_axi_CRTL_BUS_AWSIZE,
        m_axi_CRTL_BUS_AWBURST,
        m_axi_CRTL_BUS_AWLOCK,
        m_axi_CRTL_BUS_AWCACHE,
        m_axi_CRTL_BUS_AWPROT,
        m_axi_CRTL_BUS_AWQOS,
        m_axi_CRTL_BUS_AWREGION,
        m_axi_CRTL_BUS_AWUSER,
        m_axi_CRTL_BUS_WVALID,
        m_axi_CRTL_BUS_WREADY,
        m_axi_CRTL_BUS_WDATA,
        m_axi_CRTL_BUS_WSTRB,
        m_axi_CRTL_BUS_WLAST,
        m_axi_CRTL_BUS_WID,
        m_axi_CRTL_BUS_WUSER,
        m_axi_CRTL_BUS_ARVALID,
        m_axi_CRTL_BUS_ARREADY,
        m_axi_CRTL_BUS_ARADDR,
        m_axi_CRTL_BUS_ARID,
        m_axi_CRTL_BUS_ARLEN,
        m_axi_CRTL_BUS_ARSIZE,
        m_axi_CRTL_BUS_ARBURST,
        m_axi_CRTL_BUS_ARLOCK,
        m_axi_CRTL_BUS_ARCACHE,
        m_axi_CRTL_BUS_ARPROT,
        m_axi_CRTL_BUS_ARQOS,
        m_axi_CRTL_BUS_ARREGION,
        m_axi_CRTL_BUS_ARUSER,
        m_axi_CRTL_BUS_RVALID,
        m_axi_CRTL_BUS_RREADY,
        m_axi_CRTL_BUS_RDATA,
        m_axi_CRTL_BUS_RLAST,
        m_axi_CRTL_BUS_RID,
        m_axi_CRTL_BUS_RUSER,
        m_axi_CRTL_BUS_RRESP,
        m_axi_CRTL_BUS_BVALID,
        m_axi_CRTL_BUS_BREADY,
        m_axi_CRTL_BUS_BRESP,
        m_axi_CRTL_BUS_BID,
        m_axi_CRTL_BUS_BUSER
);

parameter    C_S_AXI_AXILITES_DATA_WIDTH = 32;
parameter    ap_const_int64_8 = 8;
parameter    C_S_AXI_AXILITES_ADDR_WIDTH = 6;
parameter    C_S_AXI_DATA_WIDTH = 32;
parameter    C_S_AXI_ADDR_WIDTH = 32;
parameter    ap_const_logic_1 = 1'b1;
parameter    C_M_AXI_CRTL_BUS_ID_WIDTH = 1;
parameter    C_M_AXI_CRTL_BUS_ADDR_WIDTH = 32;
parameter    C_M_AXI_CRTL_BUS_DATA_WIDTH = 32;
parameter    C_M_AXI_CRTL_BUS_AWUSER_WIDTH = 1;
parameter    C_M_AXI_CRTL_BUS_ARUSER_WIDTH = 1;
parameter    C_M_AXI_CRTL_BUS_WUSER_WIDTH = 1;
parameter    C_M_AXI_CRTL_BUS_RUSER_WIDTH = 1;
parameter    C_M_AXI_CRTL_BUS_BUSER_WIDTH = 1;
parameter    C_M_AXI_ID_WIDTH = 1;
parameter    C_M_AXI_ADDR_WIDTH = 32;
parameter    C_M_AXI_DATA_WIDTH = 32;
parameter    C_M_AXI_AWUSER_WIDTH = 1;
parameter    C_M_AXI_ARUSER_WIDTH = 1;
parameter    C_M_AXI_WUSER_WIDTH = 1;
parameter    C_M_AXI_RUSER_WIDTH = 1;
parameter    C_M_AXI_BUSER_WIDTH = 1;
parameter    C_M_AXI_CRTL_BUS_USER_VALUE = 0;
parameter    C_M_AXI_CRTL_BUS_PROT_VALUE = 0;
parameter    C_M_AXI_CRTL_BUS_CACHE_VALUE = 3;
parameter    ap_const_logic_0 = 1'b0;
parameter    ap_true = 1'b1;
parameter    ap_const_lv2_0 = 2'b00;
parameter    ap_const_lv2_1 = 2'b1;
parameter    ap_const_lv1_0 = 1'b0;
parameter    ap_const_lv1_1 = 1'b1;
parameter    ap_const_lv8_0 = 8'b00000000;
parameter    ap_const_lv8_1 = 8'b1;
parameter    C_S_AXI_AXILITES_WSTRB_WIDTH = (C_S_AXI_AXILITES_DATA_WIDTH / ap_const_int64_8);
parameter    C_S_AXI_WSTRB_WIDTH = (C_S_AXI_DATA_WIDTH / ap_const_int64_8);
parameter    C_M_AXI_CRTL_BUS_WSTRB_WIDTH = (C_M_AXI_CRTL_BUS_DATA_WIDTH / ap_const_int64_8);
parameter    C_M_AXI_WSTRB_WIDTH = (C_M_AXI_DATA_WIDTH / ap_const_int64_8);

input   s_axi_AXILiteS_AWVALID;
output   s_axi_AXILiteS_AWREADY;
input  [C_S_AXI_AXILITES_ADDR_WIDTH - 1 : 0] s_axi_AXILiteS_AWADDR;
input   s_axi_AXILiteS_WVALID;
output   s_axi_AXILiteS_WREADY;
input  [C_S_AXI_AXILITES_DATA_WIDTH - 1 : 0] s_axi_AXILiteS_WDATA;
input  [C_S_AXI_AXILITES_WSTRB_WIDTH - 1 : 0] s_axi_AXILiteS_WSTRB;
input   s_axi_AXILiteS_ARVALID;
output   s_axi_AXILiteS_ARREADY;
input  [C_S_AXI_AXILITES_ADDR_WIDTH - 1 : 0] s_axi_AXILiteS_ARADDR;
output   s_axi_AXILiteS_RVALID;
input   s_axi_AXILiteS_RREADY;
output  [C_S_AXI_AXILITES_DATA_WIDTH - 1 : 0] s_axi_AXILiteS_RDATA;
output  [1:0] s_axi_AXILiteS_RRESP;
output   s_axi_AXILiteS_BVALID;
input   s_axi_AXILiteS_BREADY;
output  [1:0] s_axi_AXILiteS_BRESP;
input   ap_clk;
input   ap_rst_n;
output   interrupt;
output   m_axi_CRTL_BUS_AWVALID;
input   m_axi_CRTL_BUS_AWREADY;
output  [C_M_AXI_CRTL_BUS_ADDR_WIDTH - 1 : 0] m_axi_CRTL_BUS_AWADDR;
output  [C_M_AXI_CRTL_BUS_ID_WIDTH - 1 : 0] m_axi_CRTL_BUS_AWID;
output  [7:0] m_axi_CRTL_BUS_AWLEN;
output  [2:0] m_axi_CRTL_BUS_AWSIZE;
output  [1:0] m_axi_CRTL_BUS_AWBURST;
output  [1:0] m_axi_CRTL_BUS_AWLOCK;
output  [3:0] m_axi_CRTL_BUS_AWCACHE;
output  [2:0] m_axi_CRTL_BUS_AWPROT;
output  [3:0] m_axi_CRTL_BUS_AWQOS;
output  [3:0] m_axi_CRTL_BUS_AWREGION;
output  [C_M_AXI_CRTL_BUS_AWUSER_WIDTH - 1 : 0] m_axi_CRTL_BUS_AWUSER;
output   m_axi_CRTL_BUS_WVALID;
input   m_axi_CRTL_BUS_WREADY;
output  [C_M_AXI_CRTL_BUS_DATA_WIDTH - 1 : 0] m_axi_CRTL_BUS_WDATA;
output  [C_M_AXI_CRTL_BUS_WSTRB_WIDTH - 1 : 0] m_axi_CRTL_BUS_WSTRB;
output   m_axi_CRTL_BUS_WLAST;
output  [C_M_AXI_CRTL_BUS_ID_WIDTH - 1 : 0] m_axi_CRTL_BUS_WID;
output  [C_M_AXI_CRTL_BUS_WUSER_WIDTH - 1 : 0] m_axi_CRTL_BUS_WUSER;
output   m_axi_CRTL_BUS_ARVALID;
input   m_axi_CRTL_BUS_ARREADY;
output  [C_M_AXI_CRTL_BUS_ADDR_WIDTH - 1 : 0] m_axi_CRTL_BUS_ARADDR;
output  [C_M_AXI_CRTL_BUS_ID_WIDTH - 1 : 0] m_axi_CRTL_BUS_ARID;
output  [7:0] m_axi_CRTL_BUS_ARLEN;
output  [2:0] m_axi_CRTL_BUS_ARSIZE;
output  [1:0] m_axi_CRTL_BUS_ARBURST;
output  [1:0] m_axi_CRTL_BUS_ARLOCK;
output  [3:0] m_axi_CRTL_BUS_ARCACHE;
output  [2:0] m_axi_CRTL_BUS_ARPROT;
output  [3:0] m_axi_CRTL_BUS_ARQOS;
output  [3:0] m_axi_CRTL_BUS_ARREGION;
output  [C_M_AXI_CRTL_BUS_ARUSER_WIDTH - 1 : 0] m_axi_CRTL_BUS_ARUSER;
input   m_axi_CRTL_BUS_RVALID;
output   m_axi_CRTL_BUS_RREADY;
input  [C_M_AXI_CRTL_BUS_DATA_WIDTH - 1 : 0] m_axi_CRTL_BUS_RDATA;
input   m_axi_CRTL_BUS_RLAST;
input  [C_M_AXI_CRTL_BUS_ID_WIDTH - 1 : 0] m_axi_CRTL_BUS_RID;
input  [C_M_AXI_CRTL_BUS_RUSER_WIDTH - 1 : 0] m_axi_CRTL_BUS_RUSER;
input  [1:0] m_axi_CRTL_BUS_RRESP;
input   m_axi_CRTL_BUS_BVALID;
output   m_axi_CRTL_BUS_BREADY;
input  [1:0] m_axi_CRTL_BUS_BRESP;
input  [C_M_AXI_CRTL_BUS_ID_WIDTH - 1 : 0] m_axi_CRTL_BUS_BID;
input  [C_M_AXI_CRTL_BUS_BUSER_WIDTH - 1 : 0] m_axi_CRTL_BUS_BUSER;

reg    ap_rst_n_inv;
wire    conv_AXILiteS_s_axi_U_ap_dummy_ce;
wire    ap_start;
wire    ap_ready;
wire    ap_done;
reg    ap_idle;
wire   [31:0] image_in;
wire   [31:0] image_out;
wire    CRTL_BUS_AWVALID;
wire    CRTL_BUS_AWREADY;
wire   [31:0] CRTL_BUS_AWADDR;
wire   [0:0] CRTL_BUS_AWID;
wire   [31:0] CRTL_BUS_AWLEN;
wire   [2:0] CRTL_BUS_AWSIZE;
wire   [1:0] CRTL_BUS_AWBURST;
wire   [1:0] CRTL_BUS_AWLOCK;
wire   [3:0] CRTL_BUS_AWCACHE;
wire   [2:0] CRTL_BUS_AWPROT;
wire   [3:0] CRTL_BUS_AWQOS;
wire   [3:0] CRTL_BUS_AWREGION;
wire   [0:0] CRTL_BUS_AWUSER;
wire    CRTL_BUS_WVALID;
wire    CRTL_BUS_WREADY;
wire   [7:0] CRTL_BUS_WDATA;
wire   [0:0] CRTL_BUS_WSTRB;
wire    CRTL_BUS_WLAST;
wire   [0:0] CRTL_BUS_WID;
wire   [0:0] CRTL_BUS_WUSER;
wire    CRTL_BUS_ARVALID;
wire    CRTL_BUS_ARREADY;
wire   [31:0] CRTL_BUS_ARADDR;
wire   [0:0] CRTL_BUS_ARID;
wire   [31:0] CRTL_BUS_ARLEN;
wire   [2:0] CRTL_BUS_ARSIZE;
wire   [1:0] CRTL_BUS_ARBURST;
wire   [1:0] CRTL_BUS_ARLOCK;
wire   [3:0] CRTL_BUS_ARCACHE;
wire   [2:0] CRTL_BUS_ARPROT;
wire   [3:0] CRTL_BUS_ARQOS;
wire   [3:0] CRTL_BUS_ARREGION;
wire   [0:0] CRTL_BUS_ARUSER;
wire    CRTL_BUS_RVALID;
wire    CRTL_BUS_RREADY;
wire   [7:0] CRTL_BUS_RDATA;
wire    CRTL_BUS_RLAST;
wire   [0:0] CRTL_BUS_RID;
wire   [0:0] CRTL_BUS_RUSER;
wire   [1:0] CRTL_BUS_RRESP;
wire    CRTL_BUS_BVALID;
wire    CRTL_BUS_BREADY;
wire   [1:0] CRTL_BUS_BRESP;
wire   [0:0] CRTL_BUS_BID;
wire   [0:0] CRTL_BUS_BUSER;
wire    conv_CRTL_BUS_m_axi_U_ap_dummy_ce;
wire    conv_Block_proc9_U0_ap_start;
wire    conv_Block_proc9_U0_ap_done;
wire    conv_Block_proc9_U0_ap_continue;
wire    conv_Block_proc9_U0_ap_idle;
wire    conv_Block_proc9_U0_ap_ready;
wire   [11:0] conv_Block_proc9_U0_src_rows_V_out_din;
wire    conv_Block_proc9_U0_src_rows_V_out_full_n;
wire    conv_Block_proc9_U0_src_rows_V_out_write;
wire   [11:0] conv_Block_proc9_U0_src_rows_V_out1_din;
wire    conv_Block_proc9_U0_src_rows_V_out1_full_n;
wire    conv_Block_proc9_U0_src_rows_V_out1_write;
wire   [11:0] conv_Block_proc9_U0_src_cols_V_out_din;
wire    conv_Block_proc9_U0_src_cols_V_out_full_n;
wire    conv_Block_proc9_U0_src_cols_V_out_write;
wire   [11:0] conv_Block_proc9_U0_src_cols_V_out2_din;
wire    conv_Block_proc9_U0_src_cols_V_out2_full_n;
wire    conv_Block_proc9_U0_src_cols_V_out2_write;
wire   [31:0] conv_Block_proc9_U0_image_out;
wire   [31:0] conv_Block_proc9_U0_image_in;
wire   [31:0] conv_Block_proc9_U0_image_out_out_din;
wire    conv_Block_proc9_U0_image_out_out_full_n;
wire    conv_Block_proc9_U0_image_out_out_write;
wire   [31:0] conv_Block_proc9_U0_image_in_out_din;
wire    conv_Block_proc9_U0_image_in_out_full_n;
wire    conv_Block_proc9_U0_image_in_out_write;
wire    conv_AXIM2Mat_U0_ap_start;
wire    conv_AXIM2Mat_U0_ap_done;
wire    conv_AXIM2Mat_U0_ap_continue;
wire    conv_AXIM2Mat_U0_ap_idle;
wire    conv_AXIM2Mat_U0_ap_ready;
wire    conv_AXIM2Mat_U0_m_axi_fb_AWVALID;
wire    conv_AXIM2Mat_U0_m_axi_fb_AWREADY;
wire   [31:0] conv_AXIM2Mat_U0_m_axi_fb_AWADDR;
wire   [0:0] conv_AXIM2Mat_U0_m_axi_fb_AWID;
wire   [31:0] conv_AXIM2Mat_U0_m_axi_fb_AWLEN;
wire   [2:0] conv_AXIM2Mat_U0_m_axi_fb_AWSIZE;
wire   [1:0] conv_AXIM2Mat_U0_m_axi_fb_AWBURST;
wire   [1:0] conv_AXIM2Mat_U0_m_axi_fb_AWLOCK;
wire   [3:0] conv_AXIM2Mat_U0_m_axi_fb_AWCACHE;
wire   [2:0] conv_AXIM2Mat_U0_m_axi_fb_AWPROT;
wire   [3:0] conv_AXIM2Mat_U0_m_axi_fb_AWQOS;
wire   [3:0] conv_AXIM2Mat_U0_m_axi_fb_AWREGION;
wire   [0:0] conv_AXIM2Mat_U0_m_axi_fb_AWUSER;
wire    conv_AXIM2Mat_U0_m_axi_fb_WVALID;
wire    conv_AXIM2Mat_U0_m_axi_fb_WREADY;
wire   [7:0] conv_AXIM2Mat_U0_m_axi_fb_WDATA;
wire   [0:0] conv_AXIM2Mat_U0_m_axi_fb_WSTRB;
wire    conv_AXIM2Mat_U0_m_axi_fb_WLAST;
wire   [0:0] conv_AXIM2Mat_U0_m_axi_fb_WID;
wire   [0:0] conv_AXIM2Mat_U0_m_axi_fb_WUSER;
wire    conv_AXIM2Mat_U0_m_axi_fb_ARVALID;
wire    conv_AXIM2Mat_U0_m_axi_fb_ARREADY;
wire   [31:0] conv_AXIM2Mat_U0_m_axi_fb_ARADDR;
wire   [0:0] conv_AXIM2Mat_U0_m_axi_fb_ARID;
wire   [31:0] conv_AXIM2Mat_U0_m_axi_fb_ARLEN;
wire   [2:0] conv_AXIM2Mat_U0_m_axi_fb_ARSIZE;
wire   [1:0] conv_AXIM2Mat_U0_m_axi_fb_ARBURST;
wire   [1:0] conv_AXIM2Mat_U0_m_axi_fb_ARLOCK;
wire   [3:0] conv_AXIM2Mat_U0_m_axi_fb_ARCACHE;
wire   [2:0] conv_AXIM2Mat_U0_m_axi_fb_ARPROT;
wire   [3:0] conv_AXIM2Mat_U0_m_axi_fb_ARQOS;
wire   [3:0] conv_AXIM2Mat_U0_m_axi_fb_ARREGION;
wire   [0:0] conv_AXIM2Mat_U0_m_axi_fb_ARUSER;
wire    conv_AXIM2Mat_U0_m_axi_fb_RVALID;
wire    conv_AXIM2Mat_U0_m_axi_fb_RREADY;
wire   [7:0] conv_AXIM2Mat_U0_m_axi_fb_RDATA;
wire    conv_AXIM2Mat_U0_m_axi_fb_RLAST;
wire   [0:0] conv_AXIM2Mat_U0_m_axi_fb_RID;
wire   [0:0] conv_AXIM2Mat_U0_m_axi_fb_RUSER;
wire   [1:0] conv_AXIM2Mat_U0_m_axi_fb_RRESP;
wire    conv_AXIM2Mat_U0_m_axi_fb_BVALID;
wire    conv_AXIM2Mat_U0_m_axi_fb_BREADY;
wire   [1:0] conv_AXIM2Mat_U0_m_axi_fb_BRESP;
wire   [0:0] conv_AXIM2Mat_U0_m_axi_fb_BID;
wire   [0:0] conv_AXIM2Mat_U0_m_axi_fb_BUSER;
wire   [31:0] conv_AXIM2Mat_U0_image_in_dout;
wire    conv_AXIM2Mat_U0_image_in_empty_n;
wire    conv_AXIM2Mat_U0_image_in_read;
wire   [11:0] conv_AXIM2Mat_U0_img_rows_V_dout;
wire    conv_AXIM2Mat_U0_img_rows_V_empty_n;
wire    conv_AXIM2Mat_U0_img_rows_V_read;
wire   [11:0] conv_AXIM2Mat_U0_img_cols_V_dout;
wire    conv_AXIM2Mat_U0_img_cols_V_empty_n;
wire    conv_AXIM2Mat_U0_img_cols_V_read;
wire   [7:0] conv_AXIM2Mat_U0_img_data_stream_V_din;
wire    conv_AXIM2Mat_U0_img_data_stream_V_full_n;
wire    conv_AXIM2Mat_U0_img_data_stream_V_write;
wire    conv_Loop_1_proc_U0_ap_start;
wire    conv_Loop_1_proc_U0_ap_done;
reg    conv_Loop_1_proc_U0_ap_continue;
wire    conv_Loop_1_proc_U0_ap_idle;
wire    conv_Loop_1_proc_U0_ap_ready;
wire   [7:0] conv_Loop_1_proc_U0_ap_return_0;
wire   [7:0] conv_Loop_1_proc_U0_ap_return_1;
wire   [7:0] conv_Loop_1_proc_U0_ap_return_2;
wire   [7:0] conv_Loop_1_proc_U0_ap_return_3;
wire   [7:0] conv_Loop_1_proc_U0_ap_return_4;
wire   [7:0] conv_Loop_1_proc_U0_ap_return_5;
wire   [7:0] conv_Loop_1_proc_U0_ap_return_6;
wire   [7:0] conv_Loop_1_proc_U0_ap_return_7;
wire   [7:0] conv_Loop_1_proc_U0_ap_return_8;
reg    ap_chn_write_conv_Loop_1_proc_U0_kernel_val_0_0_channel;
wire    kernel_val_0_0_channel_full_n;
reg    ap_reg_ready_kernel_val_0_0_channel_full_n = 1'b0;
reg    ap_sig_ready_kernel_val_0_0_channel_full_n;
reg    ap_chn_write_conv_Loop_1_proc_U0_kernel_val_0_1_channel;
wire    kernel_val_0_1_channel_full_n;
reg    ap_reg_ready_kernel_val_0_1_channel_full_n = 1'b0;
reg    ap_sig_ready_kernel_val_0_1_channel_full_n;
reg    ap_chn_write_conv_Loop_1_proc_U0_kernel_val_1_0_channel;
wire    kernel_val_1_0_channel_full_n;
reg    ap_reg_ready_kernel_val_1_0_channel_full_n = 1'b0;
reg    ap_sig_ready_kernel_val_1_0_channel_full_n;
reg    ap_chn_write_conv_Loop_1_proc_U0_kernel_val_2_0_channel;
wire    kernel_val_2_0_channel_full_n;
reg    ap_reg_ready_kernel_val_2_0_channel_full_n = 1'b0;
reg    ap_sig_ready_kernel_val_2_0_channel_full_n;
reg    ap_chn_write_conv_Loop_1_proc_U0_kernel_val_1_1_channel;
wire    kernel_val_1_1_channel_full_n;
reg    ap_reg_ready_kernel_val_1_1_channel_full_n = 1'b0;
reg    ap_sig_ready_kernel_val_1_1_channel_full_n;
reg    ap_chn_write_conv_Loop_1_proc_U0_kernel_val_1_2_channel;
wire    kernel_val_1_2_channel_full_n;
reg    ap_reg_ready_kernel_val_1_2_channel_full_n = 1'b0;
reg    ap_sig_ready_kernel_val_1_2_channel_full_n;
reg    ap_chn_write_conv_Loop_1_proc_U0_kernel_val_0_2_channel;
wire    kernel_val_0_2_channel_full_n;
reg    ap_reg_ready_kernel_val_0_2_channel_full_n = 1'b0;
reg    ap_sig_ready_kernel_val_0_2_channel_full_n;
reg    ap_chn_write_conv_Loop_1_proc_U0_kernel_val_2_2_channel;
wire    kernel_val_2_2_channel_full_n;
reg    ap_reg_ready_kernel_val_2_2_channel_full_n = 1'b0;
reg    ap_sig_ready_kernel_val_2_2_channel_full_n;
reg    ap_chn_write_conv_Loop_1_proc_U0_kernel_val_2_1_channel;
wire    kernel_val_2_1_channel_full_n;
reg    ap_reg_ready_kernel_val_2_1_channel_full_n = 1'b0;
reg    ap_sig_ready_kernel_val_2_1_channel_full_n;
wire    conv_Filter2D_U0_ap_start;
wire    conv_Filter2D_U0_ap_done;
wire    conv_Filter2D_U0_ap_continue;
wire    conv_Filter2D_U0_ap_idle;
wire    conv_Filter2D_U0_ap_ready;
wire   [11:0] conv_Filter2D_U0_p_src_rows_V_dout;
wire    conv_Filter2D_U0_p_src_rows_V_empty_n;
wire    conv_Filter2D_U0_p_src_rows_V_read;
wire   [11:0] conv_Filter2D_U0_p_src_cols_V_dout;
wire    conv_Filter2D_U0_p_src_cols_V_empty_n;
wire    conv_Filter2D_U0_p_src_cols_V_read;
wire   [7:0] conv_Filter2D_U0_p_src_data_stream_V_dout;
wire    conv_Filter2D_U0_p_src_data_stream_V_empty_n;
wire    conv_Filter2D_U0_p_src_data_stream_V_read;
wire   [7:0] conv_Filter2D_U0_p_dst_data_stream_V_din;
wire    conv_Filter2D_U0_p_dst_data_stream_V_full_n;
wire    conv_Filter2D_U0_p_dst_data_stream_V_write;
wire   [7:0] conv_Filter2D_U0_p_kernel_val_0_0_read;
wire   [7:0] conv_Filter2D_U0_p_kernel_val_0_1_read;
wire   [7:0] conv_Filter2D_U0_p_kernel_val_0_2_read;
wire   [7:0] conv_Filter2D_U0_p_kernel_val_1_0_read;
wire   [7:0] conv_Filter2D_U0_p_kernel_val_1_1_read;
wire   [7:0] conv_Filter2D_U0_p_kernel_val_1_2_read;
wire   [7:0] conv_Filter2D_U0_p_kernel_val_2_0_read;
wire   [7:0] conv_Filter2D_U0_p_kernel_val_2_1_read;
wire   [7:0] conv_Filter2D_U0_p_kernel_val_2_2_read;
reg    conv_Mat2AXIM_U0_ap_start = 1'b0;
wire    conv_Mat2AXIM_U0_ap_done;
wire    conv_Mat2AXIM_U0_ap_continue;
wire    conv_Mat2AXIM_U0_ap_idle;
wire    conv_Mat2AXIM_U0_ap_ready;
wire   [7:0] conv_Mat2AXIM_U0_img_data_stream_V_dout;
wire    conv_Mat2AXIM_U0_img_data_stream_V_empty_n;
wire    conv_Mat2AXIM_U0_img_data_stream_V_read;
wire    conv_Mat2AXIM_U0_m_axi_fb_AWVALID;
wire    conv_Mat2AXIM_U0_m_axi_fb_AWREADY;
wire   [31:0] conv_Mat2AXIM_U0_m_axi_fb_AWADDR;
wire   [0:0] conv_Mat2AXIM_U0_m_axi_fb_AWID;
wire   [31:0] conv_Mat2AXIM_U0_m_axi_fb_AWLEN;
wire   [2:0] conv_Mat2AXIM_U0_m_axi_fb_AWSIZE;
wire   [1:0] conv_Mat2AXIM_U0_m_axi_fb_AWBURST;
wire   [1:0] conv_Mat2AXIM_U0_m_axi_fb_AWLOCK;
wire   [3:0] conv_Mat2AXIM_U0_m_axi_fb_AWCACHE;
wire   [2:0] conv_Mat2AXIM_U0_m_axi_fb_AWPROT;
wire   [3:0] conv_Mat2AXIM_U0_m_axi_fb_AWQOS;
wire   [3:0] conv_Mat2AXIM_U0_m_axi_fb_AWREGION;
wire   [0:0] conv_Mat2AXIM_U0_m_axi_fb_AWUSER;
wire    conv_Mat2AXIM_U0_m_axi_fb_WVALID;
wire    conv_Mat2AXIM_U0_m_axi_fb_WREADY;
wire   [7:0] conv_Mat2AXIM_U0_m_axi_fb_WDATA;
wire   [0:0] conv_Mat2AXIM_U0_m_axi_fb_WSTRB;
wire    conv_Mat2AXIM_U0_m_axi_fb_WLAST;
wire   [0:0] conv_Mat2AXIM_U0_m_axi_fb_WID;
wire   [0:0] conv_Mat2AXIM_U0_m_axi_fb_WUSER;
wire    conv_Mat2AXIM_U0_m_axi_fb_ARVALID;
wire    conv_Mat2AXIM_U0_m_axi_fb_ARREADY;
wire   [31:0] conv_Mat2AXIM_U0_m_axi_fb_ARADDR;
wire   [0:0] conv_Mat2AXIM_U0_m_axi_fb_ARID;
wire   [31:0] conv_Mat2AXIM_U0_m_axi_fb_ARLEN;
wire   [2:0] conv_Mat2AXIM_U0_m_axi_fb_ARSIZE;
wire   [1:0] conv_Mat2AXIM_U0_m_axi_fb_ARBURST;
wire   [1:0] conv_Mat2AXIM_U0_m_axi_fb_ARLOCK;
wire   [3:0] conv_Mat2AXIM_U0_m_axi_fb_ARCACHE;
wire   [2:0] conv_Mat2AXIM_U0_m_axi_fb_ARPROT;
wire   [3:0] conv_Mat2AXIM_U0_m_axi_fb_ARQOS;
wire   [3:0] conv_Mat2AXIM_U0_m_axi_fb_ARREGION;
wire   [0:0] conv_Mat2AXIM_U0_m_axi_fb_ARUSER;
wire    conv_Mat2AXIM_U0_m_axi_fb_RVALID;
wire    conv_Mat2AXIM_U0_m_axi_fb_RREADY;
wire   [7:0] conv_Mat2AXIM_U0_m_axi_fb_RDATA;
wire    conv_Mat2AXIM_U0_m_axi_fb_RLAST;
wire   [0:0] conv_Mat2AXIM_U0_m_axi_fb_RID;
wire   [0:0] conv_Mat2AXIM_U0_m_axi_fb_RUSER;
wire   [1:0] conv_Mat2AXIM_U0_m_axi_fb_RRESP;
wire    conv_Mat2AXIM_U0_m_axi_fb_BVALID;
wire    conv_Mat2AXIM_U0_m_axi_fb_BREADY;
wire   [1:0] conv_Mat2AXIM_U0_m_axi_fb_BRESP;
wire   [0:0] conv_Mat2AXIM_U0_m_axi_fb_BID;
wire   [0:0] conv_Mat2AXIM_U0_m_axi_fb_BUSER;
wire   [31:0] conv_Mat2AXIM_U0_image_out_dout;
wire    conv_Mat2AXIM_U0_image_out_empty_n;
wire    conv_Mat2AXIM_U0_image_out_read;
wire    ap_sig_hs_continue;
wire    src_rows_V_channel_U_ap_dummy_ce;
wire   [11:0] src_rows_V_channel_din;
wire    src_rows_V_channel_full_n;
wire    src_rows_V_channel_write;
wire   [11:0] src_rows_V_channel_dout;
wire    src_rows_V_channel_empty_n;
wire    src_rows_V_channel_read;
wire    src_rows_V_channel38_U_ap_dummy_ce;
wire   [11:0] src_rows_V_channel38_din;
wire    src_rows_V_channel38_full_n;
wire    src_rows_V_channel38_write;
wire   [11:0] src_rows_V_channel38_dout;
wire    src_rows_V_channel38_empty_n;
wire    src_rows_V_channel38_read;
wire    src_cols_V_channel_U_ap_dummy_ce;
wire   [11:0] src_cols_V_channel_din;
wire    src_cols_V_channel_full_n;
wire    src_cols_V_channel_write;
wire   [11:0] src_cols_V_channel_dout;
wire    src_cols_V_channel_empty_n;
wire    src_cols_V_channel_read;
wire    src_cols_V_channel39_U_ap_dummy_ce;
wire   [11:0] src_cols_V_channel39_din;
wire    src_cols_V_channel39_full_n;
wire    src_cols_V_channel39_write;
wire   [11:0] src_cols_V_channel39_dout;
wire    src_cols_V_channel39_empty_n;
wire    src_cols_V_channel39_read;
wire    image_out_channel_U_ap_dummy_ce;
wire   [31:0] image_out_channel_din;
wire    image_out_channel_full_n;
wire    image_out_channel_write;
wire   [31:0] image_out_channel_dout;
wire    image_out_channel_empty_n;
wire    image_out_channel_read;
wire    image_in_channel_U_ap_dummy_ce;
wire   [31:0] image_in_channel_din;
wire    image_in_channel_full_n;
wire    image_in_channel_write;
wire   [31:0] image_in_channel_dout;
wire    image_in_channel_empty_n;
wire    image_in_channel_read;
wire    src_data_stream_0_V_U_ap_dummy_ce;
wire   [7:0] src_data_stream_0_V_din;
wire    src_data_stream_0_V_full_n;
wire    src_data_stream_0_V_write;
wire   [7:0] src_data_stream_0_V_dout;
wire    src_data_stream_0_V_empty_n;
wire    src_data_stream_0_V_read;
wire    kernel_val_0_0_channel_U_ap_dummy_ce;
wire   [7:0] kernel_val_0_0_channel_din;
wire    kernel_val_0_0_channel_write;
wire   [7:0] kernel_val_0_0_channel_dout;
wire    kernel_val_0_0_channel_empty_n;
wire    kernel_val_0_0_channel_read;
wire    kernel_val_0_1_channel_U_ap_dummy_ce;
wire   [7:0] kernel_val_0_1_channel_din;
wire    kernel_val_0_1_channel_write;
wire   [7:0] kernel_val_0_1_channel_dout;
wire    kernel_val_0_1_channel_empty_n;
wire    kernel_val_0_1_channel_read;
wire    kernel_val_0_2_channel_U_ap_dummy_ce;
wire   [7:0] kernel_val_0_2_channel_din;
wire    kernel_val_0_2_channel_write;
wire   [7:0] kernel_val_0_2_channel_dout;
wire    kernel_val_0_2_channel_empty_n;
wire    kernel_val_0_2_channel_read;
wire    kernel_val_1_0_channel_U_ap_dummy_ce;
wire   [7:0] kernel_val_1_0_channel_din;
wire    kernel_val_1_0_channel_write;
wire   [7:0] kernel_val_1_0_channel_dout;
wire    kernel_val_1_0_channel_empty_n;
wire    kernel_val_1_0_channel_read;
wire    kernel_val_1_1_channel_U_ap_dummy_ce;
wire   [7:0] kernel_val_1_1_channel_din;
wire    kernel_val_1_1_channel_write;
wire   [7:0] kernel_val_1_1_channel_dout;
wire    kernel_val_1_1_channel_empty_n;
wire    kernel_val_1_1_channel_read;
wire    kernel_val_1_2_channel_U_ap_dummy_ce;
wire   [7:0] kernel_val_1_2_channel_din;
wire    kernel_val_1_2_channel_write;
wire   [7:0] kernel_val_1_2_channel_dout;
wire    kernel_val_1_2_channel_empty_n;
wire    kernel_val_1_2_channel_read;
wire    kernel_val_2_0_channel_U_ap_dummy_ce;
wire   [7:0] kernel_val_2_0_channel_din;
wire    kernel_val_2_0_channel_write;
wire   [7:0] kernel_val_2_0_channel_dout;
wire    kernel_val_2_0_channel_empty_n;
wire    kernel_val_2_0_channel_read;
wire    kernel_val_2_1_channel_U_ap_dummy_ce;
wire   [7:0] kernel_val_2_1_channel_din;
wire    kernel_val_2_1_channel_write;
wire   [7:0] kernel_val_2_1_channel_dout;
wire    kernel_val_2_1_channel_empty_n;
wire    kernel_val_2_1_channel_read;
wire    kernel_val_2_2_channel_U_ap_dummy_ce;
wire   [7:0] kernel_val_2_2_channel_din;
wire    kernel_val_2_2_channel_write;
wire   [7:0] kernel_val_2_2_channel_dout;
wire    kernel_val_2_2_channel_empty_n;
wire    kernel_val_2_2_channel_read;
wire    dst_data_stream_0_V_U_ap_dummy_ce;
wire   [7:0] dst_data_stream_0_V_din;
wire    dst_data_stream_0_V_full_n;
wire    dst_data_stream_0_V_write;
wire   [7:0] dst_data_stream_0_V_dout;
wire    dst_data_stream_0_V_empty_n;
wire    dst_data_stream_0_V_read;
reg    ap_reg_procdone_conv_Block_proc9_U0 = 1'b0;
reg    ap_sig_hs_done;
reg    ap_reg_procdone_conv_AXIM2Mat_U0 = 1'b0;
reg    ap_reg_procdone_conv_Loop_1_proc_U0 = 1'b0;
reg    ap_reg_procdone_conv_Filter2D_U0 = 1'b0;
reg    ap_reg_procdone_conv_Mat2AXIM_U0 = 1'b0;
reg    ap_CS;
reg    ap_sig_top_allready;
reg    ap_reg_ready_conv_Block_proc9_U0_ap_ready = 1'b0;
reg    ap_sig_ready_conv_Block_proc9_U0_ap_ready;
reg    ap_sig_start_in_conv_Block_proc9_U0_ap_start;
reg    ap_reg_ready_conv_AXIM2Mat_U0_ap_ready = 1'b0;
reg    ap_sig_ready_conv_AXIM2Mat_U0_ap_ready;
reg    ap_sig_start_in_conv_AXIM2Mat_U0_ap_start;


conv_AXILiteS_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_AXILITES_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_AXILITES_DATA_WIDTH ))
conv_AXILiteS_s_axi_U(
    .AWVALID( s_axi_AXILiteS_AWVALID ),
    .AWREADY( s_axi_AXILiteS_AWREADY ),
    .AWADDR( s_axi_AXILiteS_AWADDR ),
    .WVALID( s_axi_AXILiteS_WVALID ),
    .WREADY( s_axi_AXILiteS_WREADY ),
    .WDATA( s_axi_AXILiteS_WDATA ),
    .WSTRB( s_axi_AXILiteS_WSTRB ),
    .ARVALID( s_axi_AXILiteS_ARVALID ),
    .ARREADY( s_axi_AXILiteS_ARREADY ),
    .ARADDR( s_axi_AXILiteS_ARADDR ),
    .RVALID( s_axi_AXILiteS_RVALID ),
    .RREADY( s_axi_AXILiteS_RREADY ),
    .RDATA( s_axi_AXILiteS_RDATA ),
    .RRESP( s_axi_AXILiteS_RRESP ),
    .BVALID( s_axi_AXILiteS_BVALID ),
    .BREADY( s_axi_AXILiteS_BREADY ),
    .BRESP( s_axi_AXILiteS_BRESP ),
    .ACLK( ap_clk ),
    .ARESET( ap_rst_n_inv ),
    .ACLK_EN( conv_AXILiteS_s_axi_U_ap_dummy_ce ),
    .ap_start( ap_start ),
    .interrupt( interrupt ),
    .ap_ready( ap_ready ),
    .ap_done( ap_done ),
    .ap_idle( ap_idle ),
    .image_in( image_in ),
    .image_out( image_out )
);

conv_CRTL_BUS_m_axi #(
    .USER_DW( 8 ),
    .USER_AW( 32 ),
    .USER_MAXREQS( 5 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_CRTL_BUS_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_CRTL_BUS_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_CRTL_BUS_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_CRTL_BUS_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_CRTL_BUS_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_CRTL_BUS_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_CRTL_BUS_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_CRTL_BUS_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_CRTL_BUS_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_CRTL_BUS_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_CRTL_BUS_CACHE_VALUE ))
conv_CRTL_BUS_m_axi_U(
    .AWVALID( m_axi_CRTL_BUS_AWVALID ),
    .AWREADY( m_axi_CRTL_BUS_AWREADY ),
    .AWADDR( m_axi_CRTL_BUS_AWADDR ),
    .AWID( m_axi_CRTL_BUS_AWID ),
    .AWLEN( m_axi_CRTL_BUS_AWLEN ),
    .AWSIZE( m_axi_CRTL_BUS_AWSIZE ),
    .AWBURST( m_axi_CRTL_BUS_AWBURST ),
    .AWLOCK( m_axi_CRTL_BUS_AWLOCK ),
    .AWCACHE( m_axi_CRTL_BUS_AWCACHE ),
    .AWPROT( m_axi_CRTL_BUS_AWPROT ),
    .AWQOS( m_axi_CRTL_BUS_AWQOS ),
    .AWREGION( m_axi_CRTL_BUS_AWREGION ),
    .AWUSER( m_axi_CRTL_BUS_AWUSER ),
    .WVALID( m_axi_CRTL_BUS_WVALID ),
    .WREADY( m_axi_CRTL_BUS_WREADY ),
    .WDATA( m_axi_CRTL_BUS_WDATA ),
    .WSTRB( m_axi_CRTL_BUS_WSTRB ),
    .WLAST( m_axi_CRTL_BUS_WLAST ),
    .WID( m_axi_CRTL_BUS_WID ),
    .WUSER( m_axi_CRTL_BUS_WUSER ),
    .ARVALID( m_axi_CRTL_BUS_ARVALID ),
    .ARREADY( m_axi_CRTL_BUS_ARREADY ),
    .ARADDR( m_axi_CRTL_BUS_ARADDR ),
    .ARID( m_axi_CRTL_BUS_ARID ),
    .ARLEN( m_axi_CRTL_BUS_ARLEN ),
    .ARSIZE( m_axi_CRTL_BUS_ARSIZE ),
    .ARBURST( m_axi_CRTL_BUS_ARBURST ),
    .ARLOCK( m_axi_CRTL_BUS_ARLOCK ),
    .ARCACHE( m_axi_CRTL_BUS_ARCACHE ),
    .ARPROT( m_axi_CRTL_BUS_ARPROT ),
    .ARQOS( m_axi_CRTL_BUS_ARQOS ),
    .ARREGION( m_axi_CRTL_BUS_ARREGION ),
    .ARUSER( m_axi_CRTL_BUS_ARUSER ),
    .RVALID( m_axi_CRTL_BUS_RVALID ),
    .RREADY( m_axi_CRTL_BUS_RREADY ),
    .RDATA( m_axi_CRTL_BUS_RDATA ),
    .RLAST( m_axi_CRTL_BUS_RLAST ),
    .RID( m_axi_CRTL_BUS_RID ),
    .RUSER( m_axi_CRTL_BUS_RUSER ),
    .RRESP( m_axi_CRTL_BUS_RRESP ),
    .BVALID( m_axi_CRTL_BUS_BVALID ),
    .BREADY( m_axi_CRTL_BUS_BREADY ),
    .BRESP( m_axi_CRTL_BUS_BRESP ),
    .BID( m_axi_CRTL_BUS_BID ),
    .BUSER( m_axi_CRTL_BUS_BUSER ),
    .ACLK( ap_clk ),
    .ARESET( ap_rst_n_inv ),
    .ACLK_EN( conv_CRTL_BUS_m_axi_U_ap_dummy_ce ),
    .I_ARVALID( CRTL_BUS_ARVALID ),
    .I_ARREADY( CRTL_BUS_ARREADY ),
    .I_ARADDR( CRTL_BUS_ARADDR ),
    .I_ARID( CRTL_BUS_ARID ),
    .I_ARLEN( CRTL_BUS_ARLEN ),
    .I_ARSIZE( CRTL_BUS_ARSIZE ),
    .I_ARLOCK( CRTL_BUS_ARLOCK ),
    .I_ARCACHE( CRTL_BUS_ARCACHE ),
    .I_ARQOS( CRTL_BUS_ARQOS ),
    .I_ARPROT( CRTL_BUS_ARPROT ),
    .I_ARUSER( CRTL_BUS_ARUSER ),
    .I_ARBURST( CRTL_BUS_ARBURST ),
    .I_ARREGION( CRTL_BUS_ARREGION ),
    .I_RVALID( CRTL_BUS_RVALID ),
    .I_RREADY( CRTL_BUS_RREADY ),
    .I_RDATA( CRTL_BUS_RDATA ),
    .I_RID( CRTL_BUS_RID ),
    .I_RUSER( CRTL_BUS_RUSER ),
    .I_RRESP( CRTL_BUS_RRESP ),
    .I_RLAST( CRTL_BUS_RLAST ),
    .I_AWVALID( CRTL_BUS_AWVALID ),
    .I_AWREADY( CRTL_BUS_AWREADY ),
    .I_AWADDR( CRTL_BUS_AWADDR ),
    .I_AWID( CRTL_BUS_AWID ),
    .I_AWLEN( CRTL_BUS_AWLEN ),
    .I_AWSIZE( CRTL_BUS_AWSIZE ),
    .I_AWLOCK( CRTL_BUS_AWLOCK ),
    .I_AWCACHE( CRTL_BUS_AWCACHE ),
    .I_AWQOS( CRTL_BUS_AWQOS ),
    .I_AWPROT( CRTL_BUS_AWPROT ),
    .I_AWUSER( CRTL_BUS_AWUSER ),
    .I_AWBURST( CRTL_BUS_AWBURST ),
    .I_AWREGION( CRTL_BUS_AWREGION ),
    .I_WVALID( CRTL_BUS_WVALID ),
    .I_WREADY( CRTL_BUS_WREADY ),
    .I_WDATA( CRTL_BUS_WDATA ),
    .I_WID( CRTL_BUS_WID ),
    .I_WUSER( CRTL_BUS_WUSER ),
    .I_WLAST( CRTL_BUS_WLAST ),
    .I_WSTRB( CRTL_BUS_WSTRB ),
    .I_BVALID( CRTL_BUS_BVALID ),
    .I_BREADY( CRTL_BUS_BREADY ),
    .I_BRESP( CRTL_BUS_BRESP ),
    .I_BID( CRTL_BUS_BID ),
    .I_BUSER( CRTL_BUS_BUSER )
);

conv_Block_proc9 conv_Block_proc9_U0(
    .ap_clk( ap_clk ),
    .ap_rst( ap_rst_n_inv ),
    .ap_start( conv_Block_proc9_U0_ap_start ),
    .ap_done( conv_Block_proc9_U0_ap_done ),
    .ap_continue( conv_Block_proc9_U0_ap_continue ),
    .ap_idle( conv_Block_proc9_U0_ap_idle ),
    .ap_ready( conv_Block_proc9_U0_ap_ready ),
    .src_rows_V_out_din( conv_Block_proc9_U0_src_rows_V_out_din ),
    .src_rows_V_out_full_n( conv_Block_proc9_U0_src_rows_V_out_full_n ),
    .src_rows_V_out_write( conv_Block_proc9_U0_src_rows_V_out_write ),
    .src_rows_V_out1_din( conv_Block_proc9_U0_src_rows_V_out1_din ),
    .src_rows_V_out1_full_n( conv_Block_proc9_U0_src_rows_V_out1_full_n ),
    .src_rows_V_out1_write( conv_Block_proc9_U0_src_rows_V_out1_write ),
    .src_cols_V_out_din( conv_Block_proc9_U0_src_cols_V_out_din ),
    .src_cols_V_out_full_n( conv_Block_proc9_U0_src_cols_V_out_full_n ),
    .src_cols_V_out_write( conv_Block_proc9_U0_src_cols_V_out_write ),
    .src_cols_V_out2_din( conv_Block_proc9_U0_src_cols_V_out2_din ),
    .src_cols_V_out2_full_n( conv_Block_proc9_U0_src_cols_V_out2_full_n ),
    .src_cols_V_out2_write( conv_Block_proc9_U0_src_cols_V_out2_write ),
    .image_out( conv_Block_proc9_U0_image_out ),
    .image_in( conv_Block_proc9_U0_image_in ),
    .image_out_out_din( conv_Block_proc9_U0_image_out_out_din ),
    .image_out_out_full_n( conv_Block_proc9_U0_image_out_out_full_n ),
    .image_out_out_write( conv_Block_proc9_U0_image_out_out_write ),
    .image_in_out_din( conv_Block_proc9_U0_image_in_out_din ),
    .image_in_out_full_n( conv_Block_proc9_U0_image_in_out_full_n ),
    .image_in_out_write( conv_Block_proc9_U0_image_in_out_write )
);

conv_AXIM2Mat conv_AXIM2Mat_U0(
    .ap_clk( ap_clk ),
    .ap_rst( ap_rst_n_inv ),
    .ap_start( conv_AXIM2Mat_U0_ap_start ),
    .ap_done( conv_AXIM2Mat_U0_ap_done ),
    .ap_continue( conv_AXIM2Mat_U0_ap_continue ),
    .ap_idle( conv_AXIM2Mat_U0_ap_idle ),
    .ap_ready( conv_AXIM2Mat_U0_ap_ready ),
    .m_axi_fb_AWVALID( conv_AXIM2Mat_U0_m_axi_fb_AWVALID ),
    .m_axi_fb_AWREADY( conv_AXIM2Mat_U0_m_axi_fb_AWREADY ),
    .m_axi_fb_AWADDR( conv_AXIM2Mat_U0_m_axi_fb_AWADDR ),
    .m_axi_fb_AWID( conv_AXIM2Mat_U0_m_axi_fb_AWID ),
    .m_axi_fb_AWLEN( conv_AXIM2Mat_U0_m_axi_fb_AWLEN ),
    .m_axi_fb_AWSIZE( conv_AXIM2Mat_U0_m_axi_fb_AWSIZE ),
    .m_axi_fb_AWBURST( conv_AXIM2Mat_U0_m_axi_fb_AWBURST ),
    .m_axi_fb_AWLOCK( conv_AXIM2Mat_U0_m_axi_fb_AWLOCK ),
    .m_axi_fb_AWCACHE( conv_AXIM2Mat_U0_m_axi_fb_AWCACHE ),
    .m_axi_fb_AWPROT( conv_AXIM2Mat_U0_m_axi_fb_AWPROT ),
    .m_axi_fb_AWQOS( conv_AXIM2Mat_U0_m_axi_fb_AWQOS ),
    .m_axi_fb_AWREGION( conv_AXIM2Mat_U0_m_axi_fb_AWREGION ),
    .m_axi_fb_AWUSER( conv_AXIM2Mat_U0_m_axi_fb_AWUSER ),
    .m_axi_fb_WVALID( conv_AXIM2Mat_U0_m_axi_fb_WVALID ),
    .m_axi_fb_WREADY( conv_AXIM2Mat_U0_m_axi_fb_WREADY ),
    .m_axi_fb_WDATA( conv_AXIM2Mat_U0_m_axi_fb_WDATA ),
    .m_axi_fb_WSTRB( conv_AXIM2Mat_U0_m_axi_fb_WSTRB ),
    .m_axi_fb_WLAST( conv_AXIM2Mat_U0_m_axi_fb_WLAST ),
    .m_axi_fb_WID( conv_AXIM2Mat_U0_m_axi_fb_WID ),
    .m_axi_fb_WUSER( conv_AXIM2Mat_U0_m_axi_fb_WUSER ),
    .m_axi_fb_ARVALID( conv_AXIM2Mat_U0_m_axi_fb_ARVALID ),
    .m_axi_fb_ARREADY( conv_AXIM2Mat_U0_m_axi_fb_ARREADY ),
    .m_axi_fb_ARADDR( conv_AXIM2Mat_U0_m_axi_fb_ARADDR ),
    .m_axi_fb_ARID( conv_AXIM2Mat_U0_m_axi_fb_ARID ),
    .m_axi_fb_ARLEN( conv_AXIM2Mat_U0_m_axi_fb_ARLEN ),
    .m_axi_fb_ARSIZE( conv_AXIM2Mat_U0_m_axi_fb_ARSIZE ),
    .m_axi_fb_ARBURST( conv_AXIM2Mat_U0_m_axi_fb_ARBURST ),
    .m_axi_fb_ARLOCK( conv_AXIM2Mat_U0_m_axi_fb_ARLOCK ),
    .m_axi_fb_ARCACHE( conv_AXIM2Mat_U0_m_axi_fb_ARCACHE ),
    .m_axi_fb_ARPROT( conv_AXIM2Mat_U0_m_axi_fb_ARPROT ),
    .m_axi_fb_ARQOS( conv_AXIM2Mat_U0_m_axi_fb_ARQOS ),
    .m_axi_fb_ARREGION( conv_AXIM2Mat_U0_m_axi_fb_ARREGION ),
    .m_axi_fb_ARUSER( conv_AXIM2Mat_U0_m_axi_fb_ARUSER ),
    .m_axi_fb_RVALID( conv_AXIM2Mat_U0_m_axi_fb_RVALID ),
    .m_axi_fb_RREADY( conv_AXIM2Mat_U0_m_axi_fb_RREADY ),
    .m_axi_fb_RDATA( conv_AXIM2Mat_U0_m_axi_fb_RDATA ),
    .m_axi_fb_RLAST( conv_AXIM2Mat_U0_m_axi_fb_RLAST ),
    .m_axi_fb_RID( conv_AXIM2Mat_U0_m_axi_fb_RID ),
    .m_axi_fb_RUSER( conv_AXIM2Mat_U0_m_axi_fb_RUSER ),
    .m_axi_fb_RRESP( conv_AXIM2Mat_U0_m_axi_fb_RRESP ),
    .m_axi_fb_BVALID( conv_AXIM2Mat_U0_m_axi_fb_BVALID ),
    .m_axi_fb_BREADY( conv_AXIM2Mat_U0_m_axi_fb_BREADY ),
    .m_axi_fb_BRESP( conv_AXIM2Mat_U0_m_axi_fb_BRESP ),
    .m_axi_fb_BID( conv_AXIM2Mat_U0_m_axi_fb_BID ),
    .m_axi_fb_BUSER( conv_AXIM2Mat_U0_m_axi_fb_BUSER ),
    .image_in_dout( conv_AXIM2Mat_U0_image_in_dout ),
    .image_in_empty_n( conv_AXIM2Mat_U0_image_in_empty_n ),
    .image_in_read( conv_AXIM2Mat_U0_image_in_read ),
    .img_rows_V_dout( conv_AXIM2Mat_U0_img_rows_V_dout ),
    .img_rows_V_empty_n( conv_AXIM2Mat_U0_img_rows_V_empty_n ),
    .img_rows_V_read( conv_AXIM2Mat_U0_img_rows_V_read ),
    .img_cols_V_dout( conv_AXIM2Mat_U0_img_cols_V_dout ),
    .img_cols_V_empty_n( conv_AXIM2Mat_U0_img_cols_V_empty_n ),
    .img_cols_V_read( conv_AXIM2Mat_U0_img_cols_V_read ),
    .img_data_stream_V_din( conv_AXIM2Mat_U0_img_data_stream_V_din ),
    .img_data_stream_V_full_n( conv_AXIM2Mat_U0_img_data_stream_V_full_n ),
    .img_data_stream_V_write( conv_AXIM2Mat_U0_img_data_stream_V_write )
);

conv_Loop_1_proc conv_Loop_1_proc_U0(
    .ap_clk( ap_clk ),
    .ap_rst( ap_rst_n_inv ),
    .ap_start( conv_Loop_1_proc_U0_ap_start ),
    .ap_done( conv_Loop_1_proc_U0_ap_done ),
    .ap_continue( conv_Loop_1_proc_U0_ap_continue ),
    .ap_idle( conv_Loop_1_proc_U0_ap_idle ),
    .ap_ready( conv_Loop_1_proc_U0_ap_ready ),
    .ap_return_0( conv_Loop_1_proc_U0_ap_return_0 ),
    .ap_return_1( conv_Loop_1_proc_U0_ap_return_1 ),
    .ap_return_2( conv_Loop_1_proc_U0_ap_return_2 ),
    .ap_return_3( conv_Loop_1_proc_U0_ap_return_3 ),
    .ap_return_4( conv_Loop_1_proc_U0_ap_return_4 ),
    .ap_return_5( conv_Loop_1_proc_U0_ap_return_5 ),
    .ap_return_6( conv_Loop_1_proc_U0_ap_return_6 ),
    .ap_return_7( conv_Loop_1_proc_U0_ap_return_7 ),
    .ap_return_8( conv_Loop_1_proc_U0_ap_return_8 )
);

conv_Filter2D conv_Filter2D_U0(
    .ap_clk( ap_clk ),
    .ap_rst( ap_rst_n_inv ),
    .ap_start( conv_Filter2D_U0_ap_start ),
    .ap_done( conv_Filter2D_U0_ap_done ),
    .ap_continue( conv_Filter2D_U0_ap_continue ),
    .ap_idle( conv_Filter2D_U0_ap_idle ),
    .ap_ready( conv_Filter2D_U0_ap_ready ),
    .p_src_rows_V_dout( conv_Filter2D_U0_p_src_rows_V_dout ),
    .p_src_rows_V_empty_n( conv_Filter2D_U0_p_src_rows_V_empty_n ),
    .p_src_rows_V_read( conv_Filter2D_U0_p_src_rows_V_read ),
    .p_src_cols_V_dout( conv_Filter2D_U0_p_src_cols_V_dout ),
    .p_src_cols_V_empty_n( conv_Filter2D_U0_p_src_cols_V_empty_n ),
    .p_src_cols_V_read( conv_Filter2D_U0_p_src_cols_V_read ),
    .p_src_data_stream_V_dout( conv_Filter2D_U0_p_src_data_stream_V_dout ),
    .p_src_data_stream_V_empty_n( conv_Filter2D_U0_p_src_data_stream_V_empty_n ),
    .p_src_data_stream_V_read( conv_Filter2D_U0_p_src_data_stream_V_read ),
    .p_dst_data_stream_V_din( conv_Filter2D_U0_p_dst_data_stream_V_din ),
    .p_dst_data_stream_V_full_n( conv_Filter2D_U0_p_dst_data_stream_V_full_n ),
    .p_dst_data_stream_V_write( conv_Filter2D_U0_p_dst_data_stream_V_write ),
    .p_kernel_val_0_0_read( conv_Filter2D_U0_p_kernel_val_0_0_read ),
    .p_kernel_val_0_1_read( conv_Filter2D_U0_p_kernel_val_0_1_read ),
    .p_kernel_val_0_2_read( conv_Filter2D_U0_p_kernel_val_0_2_read ),
    .p_kernel_val_1_0_read( conv_Filter2D_U0_p_kernel_val_1_0_read ),
    .p_kernel_val_1_1_read( conv_Filter2D_U0_p_kernel_val_1_1_read ),
    .p_kernel_val_1_2_read( conv_Filter2D_U0_p_kernel_val_1_2_read ),
    .p_kernel_val_2_0_read( conv_Filter2D_U0_p_kernel_val_2_0_read ),
    .p_kernel_val_2_1_read( conv_Filter2D_U0_p_kernel_val_2_1_read ),
    .p_kernel_val_2_2_read( conv_Filter2D_U0_p_kernel_val_2_2_read )
);

conv_Mat2AXIM conv_Mat2AXIM_U0(
    .ap_clk( ap_clk ),
    .ap_rst( ap_rst_n_inv ),
    .ap_start( conv_Mat2AXIM_U0_ap_start ),
    .ap_done( conv_Mat2AXIM_U0_ap_done ),
    .ap_continue( conv_Mat2AXIM_U0_ap_continue ),
    .ap_idle( conv_Mat2AXIM_U0_ap_idle ),
    .ap_ready( conv_Mat2AXIM_U0_ap_ready ),
    .img_data_stream_V_dout( conv_Mat2AXIM_U0_img_data_stream_V_dout ),
    .img_data_stream_V_empty_n( conv_Mat2AXIM_U0_img_data_stream_V_empty_n ),
    .img_data_stream_V_read( conv_Mat2AXIM_U0_img_data_stream_V_read ),
    .m_axi_fb_AWVALID( conv_Mat2AXIM_U0_m_axi_fb_AWVALID ),
    .m_axi_fb_AWREADY( conv_Mat2AXIM_U0_m_axi_fb_AWREADY ),
    .m_axi_fb_AWADDR( conv_Mat2AXIM_U0_m_axi_fb_AWADDR ),
    .m_axi_fb_AWID( conv_Mat2AXIM_U0_m_axi_fb_AWID ),
    .m_axi_fb_AWLEN( conv_Mat2AXIM_U0_m_axi_fb_AWLEN ),
    .m_axi_fb_AWSIZE( conv_Mat2AXIM_U0_m_axi_fb_AWSIZE ),
    .m_axi_fb_AWBURST( conv_Mat2AXIM_U0_m_axi_fb_AWBURST ),
    .m_axi_fb_AWLOCK( conv_Mat2AXIM_U0_m_axi_fb_AWLOCK ),
    .m_axi_fb_AWCACHE( conv_Mat2AXIM_U0_m_axi_fb_AWCACHE ),
    .m_axi_fb_AWPROT( conv_Mat2AXIM_U0_m_axi_fb_AWPROT ),
    .m_axi_fb_AWQOS( conv_Mat2AXIM_U0_m_axi_fb_AWQOS ),
    .m_axi_fb_AWREGION( conv_Mat2AXIM_U0_m_axi_fb_AWREGION ),
    .m_axi_fb_AWUSER( conv_Mat2AXIM_U0_m_axi_fb_AWUSER ),
    .m_axi_fb_WVALID( conv_Mat2AXIM_U0_m_axi_fb_WVALID ),
    .m_axi_fb_WREADY( conv_Mat2AXIM_U0_m_axi_fb_WREADY ),
    .m_axi_fb_WDATA( conv_Mat2AXIM_U0_m_axi_fb_WDATA ),
    .m_axi_fb_WSTRB( conv_Mat2AXIM_U0_m_axi_fb_WSTRB ),
    .m_axi_fb_WLAST( conv_Mat2AXIM_U0_m_axi_fb_WLAST ),
    .m_axi_fb_WID( conv_Mat2AXIM_U0_m_axi_fb_WID ),
    .m_axi_fb_WUSER( conv_Mat2AXIM_U0_m_axi_fb_WUSER ),
    .m_axi_fb_ARVALID( conv_Mat2AXIM_U0_m_axi_fb_ARVALID ),
    .m_axi_fb_ARREADY( conv_Mat2AXIM_U0_m_axi_fb_ARREADY ),
    .m_axi_fb_ARADDR( conv_Mat2AXIM_U0_m_axi_fb_ARADDR ),
    .m_axi_fb_ARID( conv_Mat2AXIM_U0_m_axi_fb_ARID ),
    .m_axi_fb_ARLEN( conv_Mat2AXIM_U0_m_axi_fb_ARLEN ),
    .m_axi_fb_ARSIZE( conv_Mat2AXIM_U0_m_axi_fb_ARSIZE ),
    .m_axi_fb_ARBURST( conv_Mat2AXIM_U0_m_axi_fb_ARBURST ),
    .m_axi_fb_ARLOCK( conv_Mat2AXIM_U0_m_axi_fb_ARLOCK ),
    .m_axi_fb_ARCACHE( conv_Mat2AXIM_U0_m_axi_fb_ARCACHE ),
    .m_axi_fb_ARPROT( conv_Mat2AXIM_U0_m_axi_fb_ARPROT ),
    .m_axi_fb_ARQOS( conv_Mat2AXIM_U0_m_axi_fb_ARQOS ),
    .m_axi_fb_ARREGION( conv_Mat2AXIM_U0_m_axi_fb_ARREGION ),
    .m_axi_fb_ARUSER( conv_Mat2AXIM_U0_m_axi_fb_ARUSER ),
    .m_axi_fb_RVALID( conv_Mat2AXIM_U0_m_axi_fb_RVALID ),
    .m_axi_fb_RREADY( conv_Mat2AXIM_U0_m_axi_fb_RREADY ),
    .m_axi_fb_RDATA( conv_Mat2AXIM_U0_m_axi_fb_RDATA ),
    .m_axi_fb_RLAST( conv_Mat2AXIM_U0_m_axi_fb_RLAST ),
    .m_axi_fb_RID( conv_Mat2AXIM_U0_m_axi_fb_RID ),
    .m_axi_fb_RUSER( conv_Mat2AXIM_U0_m_axi_fb_RUSER ),
    .m_axi_fb_RRESP( conv_Mat2AXIM_U0_m_axi_fb_RRESP ),
    .m_axi_fb_BVALID( conv_Mat2AXIM_U0_m_axi_fb_BVALID ),
    .m_axi_fb_BREADY( conv_Mat2AXIM_U0_m_axi_fb_BREADY ),
    .m_axi_fb_BRESP( conv_Mat2AXIM_U0_m_axi_fb_BRESP ),
    .m_axi_fb_BID( conv_Mat2AXIM_U0_m_axi_fb_BID ),
    .m_axi_fb_BUSER( conv_Mat2AXIM_U0_m_axi_fb_BUSER ),
    .image_out_dout( conv_Mat2AXIM_U0_image_out_dout ),
    .image_out_empty_n( conv_Mat2AXIM_U0_image_out_empty_n ),
    .image_out_read( conv_Mat2AXIM_U0_image_out_read )
);

FIFO_conv_src_rows_V_channel src_rows_V_channel_U(
    .clk( ap_clk ),
    .reset( ap_rst_n_inv ),
    .if_read_ce( src_rows_V_channel_U_ap_dummy_ce ),
    .if_write_ce( src_rows_V_channel_U_ap_dummy_ce ),
    .if_din( src_rows_V_channel_din ),
    .if_full_n( src_rows_V_channel_full_n ),
    .if_write( src_rows_V_channel_write ),
    .if_dout( src_rows_V_channel_dout ),
    .if_empty_n( src_rows_V_channel_empty_n ),
    .if_read( src_rows_V_channel_read )
);

FIFO_conv_src_rows_V_channel38 src_rows_V_channel38_U(
    .clk( ap_clk ),
    .reset( ap_rst_n_inv ),
    .if_read_ce( src_rows_V_channel38_U_ap_dummy_ce ),
    .if_write_ce( src_rows_V_channel38_U_ap_dummy_ce ),
    .if_din( src_rows_V_channel38_din ),
    .if_full_n( src_rows_V_channel38_full_n ),
    .if_write( src_rows_V_channel38_write ),
    .if_dout( src_rows_V_channel38_dout ),
    .if_empty_n( src_rows_V_channel38_empty_n ),
    .if_read( src_rows_V_channel38_read )
);

FIFO_conv_src_cols_V_channel src_cols_V_channel_U(
    .clk( ap_clk ),
    .reset( ap_rst_n_inv ),
    .if_read_ce( src_cols_V_channel_U_ap_dummy_ce ),
    .if_write_ce( src_cols_V_channel_U_ap_dummy_ce ),
    .if_din( src_cols_V_channel_din ),
    .if_full_n( src_cols_V_channel_full_n ),
    .if_write( src_cols_V_channel_write ),
    .if_dout( src_cols_V_channel_dout ),
    .if_empty_n( src_cols_V_channel_empty_n ),
    .if_read( src_cols_V_channel_read )
);

FIFO_conv_src_cols_V_channel39 src_cols_V_channel39_U(
    .clk( ap_clk ),
    .reset( ap_rst_n_inv ),
    .if_read_ce( src_cols_V_channel39_U_ap_dummy_ce ),
    .if_write_ce( src_cols_V_channel39_U_ap_dummy_ce ),
    .if_din( src_cols_V_channel39_din ),
    .if_full_n( src_cols_V_channel39_full_n ),
    .if_write( src_cols_V_channel39_write ),
    .if_dout( src_cols_V_channel39_dout ),
    .if_empty_n( src_cols_V_channel39_empty_n ),
    .if_read( src_cols_V_channel39_read )
);

FIFO_conv_image_out_channel image_out_channel_U(
    .clk( ap_clk ),
    .reset( ap_rst_n_inv ),
    .if_read_ce( image_out_channel_U_ap_dummy_ce ),
    .if_write_ce( image_out_channel_U_ap_dummy_ce ),
    .if_din( image_out_channel_din ),
    .if_full_n( image_out_channel_full_n ),
    .if_write( image_out_channel_write ),
    .if_dout( image_out_channel_dout ),
    .if_empty_n( image_out_channel_empty_n ),
    .if_read( image_out_channel_read )
);

FIFO_conv_image_in_channel image_in_channel_U(
    .clk( ap_clk ),
    .reset( ap_rst_n_inv ),
    .if_read_ce( image_in_channel_U_ap_dummy_ce ),
    .if_write_ce( image_in_channel_U_ap_dummy_ce ),
    .if_din( image_in_channel_din ),
    .if_full_n( image_in_channel_full_n ),
    .if_write( image_in_channel_write ),
    .if_dout( image_in_channel_dout ),
    .if_empty_n( image_in_channel_empty_n ),
    .if_read( image_in_channel_read )
);

FIFO_conv_src_data_stream_0_V src_data_stream_0_V_U(
    .clk( ap_clk ),
    .reset( ap_rst_n_inv ),
    .if_read_ce( src_data_stream_0_V_U_ap_dummy_ce ),
    .if_write_ce( src_data_stream_0_V_U_ap_dummy_ce ),
    .if_din( src_data_stream_0_V_din ),
    .if_full_n( src_data_stream_0_V_full_n ),
    .if_write( src_data_stream_0_V_write ),
    .if_dout( src_data_stream_0_V_dout ),
    .if_empty_n( src_data_stream_0_V_empty_n ),
    .if_read( src_data_stream_0_V_read )
);

FIFO_conv_kernel_val_0_0_channel kernel_val_0_0_channel_U(
    .clk( ap_clk ),
    .reset( ap_rst_n_inv ),
    .if_read_ce( kernel_val_0_0_channel_U_ap_dummy_ce ),
    .if_write_ce( kernel_val_0_0_channel_U_ap_dummy_ce ),
    .if_din( kernel_val_0_0_channel_din ),
    .if_full_n( kernel_val_0_0_channel_full_n ),
    .if_write( kernel_val_0_0_channel_write ),
    .if_dout( kernel_val_0_0_channel_dout ),
    .if_empty_n( kernel_val_0_0_channel_empty_n ),
    .if_read( kernel_val_0_0_channel_read )
);

FIFO_conv_kernel_val_0_1_channel kernel_val_0_1_channel_U(
    .clk( ap_clk ),
    .reset( ap_rst_n_inv ),
    .if_read_ce( kernel_val_0_1_channel_U_ap_dummy_ce ),
    .if_write_ce( kernel_val_0_1_channel_U_ap_dummy_ce ),
    .if_din( kernel_val_0_1_channel_din ),
    .if_full_n( kernel_val_0_1_channel_full_n ),
    .if_write( kernel_val_0_1_channel_write ),
    .if_dout( kernel_val_0_1_channel_dout ),
    .if_empty_n( kernel_val_0_1_channel_empty_n ),
    .if_read( kernel_val_0_1_channel_read )
);

FIFO_conv_kernel_val_0_2_channel kernel_val_0_2_channel_U(
    .clk( ap_clk ),
    .reset( ap_rst_n_inv ),
    .if_read_ce( kernel_val_0_2_channel_U_ap_dummy_ce ),
    .if_write_ce( kernel_val_0_2_channel_U_ap_dummy_ce ),
    .if_din( kernel_val_0_2_channel_din ),
    .if_full_n( kernel_val_0_2_channel_full_n ),
    .if_write( kernel_val_0_2_channel_write ),
    .if_dout( kernel_val_0_2_channel_dout ),
    .if_empty_n( kernel_val_0_2_channel_empty_n ),
    .if_read( kernel_val_0_2_channel_read )
);

FIFO_conv_kernel_val_1_0_channel kernel_val_1_0_channel_U(
    .clk( ap_clk ),
    .reset( ap_rst_n_inv ),
    .if_read_ce( kernel_val_1_0_channel_U_ap_dummy_ce ),
    .if_write_ce( kernel_val_1_0_channel_U_ap_dummy_ce ),
    .if_din( kernel_val_1_0_channel_din ),
    .if_full_n( kernel_val_1_0_channel_full_n ),
    .if_write( kernel_val_1_0_channel_write ),
    .if_dout( kernel_val_1_0_channel_dout ),
    .if_empty_n( kernel_val_1_0_channel_empty_n ),
    .if_read( kernel_val_1_0_channel_read )
);

FIFO_conv_kernel_val_1_1_channel kernel_val_1_1_channel_U(
    .clk( ap_clk ),
    .reset( ap_rst_n_inv ),
    .if_read_ce( kernel_val_1_1_channel_U_ap_dummy_ce ),
    .if_write_ce( kernel_val_1_1_channel_U_ap_dummy_ce ),
    .if_din( kernel_val_1_1_channel_din ),
    .if_full_n( kernel_val_1_1_channel_full_n ),
    .if_write( kernel_val_1_1_channel_write ),
    .if_dout( kernel_val_1_1_channel_dout ),
    .if_empty_n( kernel_val_1_1_channel_empty_n ),
    .if_read( kernel_val_1_1_channel_read )
);

FIFO_conv_kernel_val_1_2_channel kernel_val_1_2_channel_U(
    .clk( ap_clk ),
    .reset( ap_rst_n_inv ),
    .if_read_ce( kernel_val_1_2_channel_U_ap_dummy_ce ),
    .if_write_ce( kernel_val_1_2_channel_U_ap_dummy_ce ),
    .if_din( kernel_val_1_2_channel_din ),
    .if_full_n( kernel_val_1_2_channel_full_n ),
    .if_write( kernel_val_1_2_channel_write ),
    .if_dout( kernel_val_1_2_channel_dout ),
    .if_empty_n( kernel_val_1_2_channel_empty_n ),
    .if_read( kernel_val_1_2_channel_read )
);

FIFO_conv_kernel_val_2_0_channel kernel_val_2_0_channel_U(
    .clk( ap_clk ),
    .reset( ap_rst_n_inv ),
    .if_read_ce( kernel_val_2_0_channel_U_ap_dummy_ce ),
    .if_write_ce( kernel_val_2_0_channel_U_ap_dummy_ce ),
    .if_din( kernel_val_2_0_channel_din ),
    .if_full_n( kernel_val_2_0_channel_full_n ),
    .if_write( kernel_val_2_0_channel_write ),
    .if_dout( kernel_val_2_0_channel_dout ),
    .if_empty_n( kernel_val_2_0_channel_empty_n ),
    .if_read( kernel_val_2_0_channel_read )
);

FIFO_conv_kernel_val_2_1_channel kernel_val_2_1_channel_U(
    .clk( ap_clk ),
    .reset( ap_rst_n_inv ),
    .if_read_ce( kernel_val_2_1_channel_U_ap_dummy_ce ),
    .if_write_ce( kernel_val_2_1_channel_U_ap_dummy_ce ),
    .if_din( kernel_val_2_1_channel_din ),
    .if_full_n( kernel_val_2_1_channel_full_n ),
    .if_write( kernel_val_2_1_channel_write ),
    .if_dout( kernel_val_2_1_channel_dout ),
    .if_empty_n( kernel_val_2_1_channel_empty_n ),
    .if_read( kernel_val_2_1_channel_read )
);

FIFO_conv_kernel_val_2_2_channel kernel_val_2_2_channel_U(
    .clk( ap_clk ),
    .reset( ap_rst_n_inv ),
    .if_read_ce( kernel_val_2_2_channel_U_ap_dummy_ce ),
    .if_write_ce( kernel_val_2_2_channel_U_ap_dummy_ce ),
    .if_din( kernel_val_2_2_channel_din ),
    .if_full_n( kernel_val_2_2_channel_full_n ),
    .if_write( kernel_val_2_2_channel_write ),
    .if_dout( kernel_val_2_2_channel_dout ),
    .if_empty_n( kernel_val_2_2_channel_empty_n ),
    .if_read( kernel_val_2_2_channel_read )
);

FIFO_conv_dst_data_stream_0_V dst_data_stream_0_V_U(
    .clk( ap_clk ),
    .reset( ap_rst_n_inv ),
    .if_read_ce( dst_data_stream_0_V_U_ap_dummy_ce ),
    .if_write_ce( dst_data_stream_0_V_U_ap_dummy_ce ),
    .if_din( dst_data_stream_0_V_din ),
    .if_full_n( dst_data_stream_0_V_full_n ),
    .if_write( dst_data_stream_0_V_write ),
    .if_dout( dst_data_stream_0_V_dout ),
    .if_empty_n( dst_data_stream_0_V_empty_n ),
    .if_read( dst_data_stream_0_V_read )
);



always @ (posedge ap_clk) begin : ap_ret_ap_reg_procdone_conv_AXIM2Mat_U0
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_procdone_conv_AXIM2Mat_U0 <= ap_const_logic_0;
    end else begin
        if ((ap_const_logic_1 == ap_sig_hs_done)) begin
            ap_reg_procdone_conv_AXIM2Mat_U0 <= ap_const_logic_0;
        end else if ((ap_const_logic_1 == conv_AXIM2Mat_U0_ap_done)) begin
            ap_reg_procdone_conv_AXIM2Mat_U0 <= ap_const_logic_1;
        end
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_reg_procdone_conv_Block_proc9_U0
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_procdone_conv_Block_proc9_U0 <= ap_const_logic_0;
    end else begin
        if ((ap_const_logic_1 == ap_sig_hs_done)) begin
            ap_reg_procdone_conv_Block_proc9_U0 <= ap_const_logic_0;
        end else if ((ap_const_logic_1 == conv_Block_proc9_U0_ap_done)) begin
            ap_reg_procdone_conv_Block_proc9_U0 <= ap_const_logic_1;
        end
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_reg_procdone_conv_Filter2D_U0
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_procdone_conv_Filter2D_U0 <= ap_const_logic_0;
    end else begin
        if ((ap_const_logic_1 == ap_sig_hs_done)) begin
            ap_reg_procdone_conv_Filter2D_U0 <= ap_const_logic_0;
        end else if ((ap_const_logic_1 == conv_Filter2D_U0_ap_done)) begin
            ap_reg_procdone_conv_Filter2D_U0 <= ap_const_logic_1;
        end
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_reg_procdone_conv_Loop_1_proc_U0
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_procdone_conv_Loop_1_proc_U0 <= ap_const_logic_0;
    end else begin
        if ((ap_const_logic_1 == ap_sig_hs_done)) begin
            ap_reg_procdone_conv_Loop_1_proc_U0 <= ap_const_logic_0;
        end else if ((ap_const_logic_1 == conv_Loop_1_proc_U0_ap_done)) begin
            ap_reg_procdone_conv_Loop_1_proc_U0 <= ap_const_logic_1;
        end
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_reg_procdone_conv_Mat2AXIM_U0
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_procdone_conv_Mat2AXIM_U0 <= ap_const_logic_0;
    end else begin
        if ((ap_const_logic_1 == ap_sig_hs_done)) begin
            ap_reg_procdone_conv_Mat2AXIM_U0 <= ap_const_logic_0;
        end else if ((ap_const_logic_1 == conv_Mat2AXIM_U0_ap_done)) begin
            ap_reg_procdone_conv_Mat2AXIM_U0 <= ap_const_logic_1;
        end
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_reg_ready_conv_AXIM2Mat_U0_ap_ready
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_ready_conv_AXIM2Mat_U0_ap_ready <= ap_const_logic_0;
    end else begin
        if (((ap_const_logic_1 == ap_start) & (ap_const_logic_1 == ap_sig_top_allready))) begin
            ap_reg_ready_conv_AXIM2Mat_U0_ap_ready <= ap_const_logic_0;
        end else if ((ap_const_logic_1 == conv_AXIM2Mat_U0_ap_ready)) begin
            ap_reg_ready_conv_AXIM2Mat_U0_ap_ready <= ap_const_logic_1;
        end
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_reg_ready_conv_Block_proc9_U0_ap_ready
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_ready_conv_Block_proc9_U0_ap_ready <= ap_const_logic_0;
    end else begin
        if (((ap_const_logic_1 == ap_start) & (ap_const_logic_1 == ap_sig_top_allready))) begin
            ap_reg_ready_conv_Block_proc9_U0_ap_ready <= ap_const_logic_0;
        end else if ((ap_const_logic_1 == conv_Block_proc9_U0_ap_ready)) begin
            ap_reg_ready_conv_Block_proc9_U0_ap_ready <= ap_const_logic_1;
        end
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_reg_ready_kernel_val_0_0_channel_full_n
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_ready_kernel_val_0_0_channel_full_n <= ap_const_logic_0;
    end else begin
        if (((ap_const_logic_1 == conv_Loop_1_proc_U0_ap_done) & (ap_const_logic_1 == conv_Loop_1_proc_U0_ap_continue))) begin
            ap_reg_ready_kernel_val_0_0_channel_full_n <= ap_const_logic_0;
        end else if (((ap_const_logic_1 == conv_Loop_1_proc_U0_ap_done) & (ap_const_logic_1 == kernel_val_0_0_channel_full_n))) begin
            ap_reg_ready_kernel_val_0_0_channel_full_n <= ap_const_logic_1;
        end
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_reg_ready_kernel_val_0_1_channel_full_n
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_ready_kernel_val_0_1_channel_full_n <= ap_const_logic_0;
    end else begin
        if (((ap_const_logic_1 == conv_Loop_1_proc_U0_ap_done) & (ap_const_logic_1 == conv_Loop_1_proc_U0_ap_continue))) begin
            ap_reg_ready_kernel_val_0_1_channel_full_n <= ap_const_logic_0;
        end else if (((ap_const_logic_1 == conv_Loop_1_proc_U0_ap_done) & (ap_const_logic_1 == kernel_val_0_1_channel_full_n))) begin
            ap_reg_ready_kernel_val_0_1_channel_full_n <= ap_const_logic_1;
        end
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_reg_ready_kernel_val_0_2_channel_full_n
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_ready_kernel_val_0_2_channel_full_n <= ap_const_logic_0;
    end else begin
        if (((ap_const_logic_1 == conv_Loop_1_proc_U0_ap_done) & (ap_const_logic_1 == conv_Loop_1_proc_U0_ap_continue))) begin
            ap_reg_ready_kernel_val_0_2_channel_full_n <= ap_const_logic_0;
        end else if (((ap_const_logic_1 == conv_Loop_1_proc_U0_ap_done) & (ap_const_logic_1 == kernel_val_0_2_channel_full_n))) begin
            ap_reg_ready_kernel_val_0_2_channel_full_n <= ap_const_logic_1;
        end
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_reg_ready_kernel_val_1_0_channel_full_n
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_ready_kernel_val_1_0_channel_full_n <= ap_const_logic_0;
    end else begin
        if (((ap_const_logic_1 == conv_Loop_1_proc_U0_ap_done) & (ap_const_logic_1 == conv_Loop_1_proc_U0_ap_continue))) begin
            ap_reg_ready_kernel_val_1_0_channel_full_n <= ap_const_logic_0;
        end else if (((ap_const_logic_1 == conv_Loop_1_proc_U0_ap_done) & (ap_const_logic_1 == kernel_val_1_0_channel_full_n))) begin
            ap_reg_ready_kernel_val_1_0_channel_full_n <= ap_const_logic_1;
        end
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_reg_ready_kernel_val_1_1_channel_full_n
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_ready_kernel_val_1_1_channel_full_n <= ap_const_logic_0;
    end else begin
        if (((ap_const_logic_1 == conv_Loop_1_proc_U0_ap_done) & (ap_const_logic_1 == conv_Loop_1_proc_U0_ap_continue))) begin
            ap_reg_ready_kernel_val_1_1_channel_full_n <= ap_const_logic_0;
        end else if (((ap_const_logic_1 == conv_Loop_1_proc_U0_ap_done) & (ap_const_logic_1 == kernel_val_1_1_channel_full_n))) begin
            ap_reg_ready_kernel_val_1_1_channel_full_n <= ap_const_logic_1;
        end
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_reg_ready_kernel_val_1_2_channel_full_n
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_ready_kernel_val_1_2_channel_full_n <= ap_const_logic_0;
    end else begin
        if (((ap_const_logic_1 == conv_Loop_1_proc_U0_ap_done) & (ap_const_logic_1 == conv_Loop_1_proc_U0_ap_continue))) begin
            ap_reg_ready_kernel_val_1_2_channel_full_n <= ap_const_logic_0;
        end else if (((ap_const_logic_1 == conv_Loop_1_proc_U0_ap_done) & (ap_const_logic_1 == kernel_val_1_2_channel_full_n))) begin
            ap_reg_ready_kernel_val_1_2_channel_full_n <= ap_const_logic_1;
        end
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_reg_ready_kernel_val_2_0_channel_full_n
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_ready_kernel_val_2_0_channel_full_n <= ap_const_logic_0;
    end else begin
        if (((ap_const_logic_1 == conv_Loop_1_proc_U0_ap_done) & (ap_const_logic_1 == conv_Loop_1_proc_U0_ap_continue))) begin
            ap_reg_ready_kernel_val_2_0_channel_full_n <= ap_const_logic_0;
        end else if (((ap_const_logic_1 == conv_Loop_1_proc_U0_ap_done) & (ap_const_logic_1 == kernel_val_2_0_channel_full_n))) begin
            ap_reg_ready_kernel_val_2_0_channel_full_n <= ap_const_logic_1;
        end
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_reg_ready_kernel_val_2_1_channel_full_n
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_ready_kernel_val_2_1_channel_full_n <= ap_const_logic_0;
    end else begin
        if (((ap_const_logic_1 == conv_Loop_1_proc_U0_ap_done) & (ap_const_logic_1 == conv_Loop_1_proc_U0_ap_continue))) begin
            ap_reg_ready_kernel_val_2_1_channel_full_n <= ap_const_logic_0;
        end else if (((ap_const_logic_1 == conv_Loop_1_proc_U0_ap_done) & (ap_const_logic_1 == kernel_val_2_1_channel_full_n))) begin
            ap_reg_ready_kernel_val_2_1_channel_full_n <= ap_const_logic_1;
        end
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_reg_ready_kernel_val_2_2_channel_full_n
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_ready_kernel_val_2_2_channel_full_n <= ap_const_logic_0;
    end else begin
        if (((ap_const_logic_1 == conv_Loop_1_proc_U0_ap_done) & (ap_const_logic_1 == conv_Loop_1_proc_U0_ap_continue))) begin
            ap_reg_ready_kernel_val_2_2_channel_full_n <= ap_const_logic_0;
        end else if (((ap_const_logic_1 == conv_Loop_1_proc_U0_ap_done) & (ap_const_logic_1 == kernel_val_2_2_channel_full_n))) begin
            ap_reg_ready_kernel_val_2_2_channel_full_n <= ap_const_logic_1;
        end
    end
end

always @ (posedge ap_clk) begin : ap_ret_conv_Mat2AXIM_U0_ap_start
    if (ap_rst_n_inv == 1'b1) begin
        conv_Mat2AXIM_U0_ap_start <= ap_const_logic_0;
    end else begin
        conv_Mat2AXIM_U0_ap_start <= ap_const_logic_1;
    end
end

always @ (posedge ap_clk) begin
    ap_CS <= ap_const_logic_0;
end

always @ (conv_Loop_1_proc_U0_ap_done or ap_reg_ready_kernel_val_0_0_channel_full_n) begin
    if ((ap_const_logic_1 == ap_reg_ready_kernel_val_0_0_channel_full_n)) begin
        ap_chn_write_conv_Loop_1_proc_U0_kernel_val_0_0_channel = ap_const_logic_0;
    end else begin
        ap_chn_write_conv_Loop_1_proc_U0_kernel_val_0_0_channel = conv_Loop_1_proc_U0_ap_done;
    end
end

always @ (conv_Loop_1_proc_U0_ap_done or ap_reg_ready_kernel_val_0_1_channel_full_n) begin
    if ((ap_const_logic_1 == ap_reg_ready_kernel_val_0_1_channel_full_n)) begin
        ap_chn_write_conv_Loop_1_proc_U0_kernel_val_0_1_channel = ap_const_logic_0;
    end else begin
        ap_chn_write_conv_Loop_1_proc_U0_kernel_val_0_1_channel = conv_Loop_1_proc_U0_ap_done;
    end
end

always @ (conv_Loop_1_proc_U0_ap_done or ap_reg_ready_kernel_val_0_2_channel_full_n) begin
    if ((ap_const_logic_1 == ap_reg_ready_kernel_val_0_2_channel_full_n)) begin
        ap_chn_write_conv_Loop_1_proc_U0_kernel_val_0_2_channel = ap_const_logic_0;
    end else begin
        ap_chn_write_conv_Loop_1_proc_U0_kernel_val_0_2_channel = conv_Loop_1_proc_U0_ap_done;
    end
end

always @ (conv_Loop_1_proc_U0_ap_done or ap_reg_ready_kernel_val_1_0_channel_full_n) begin
    if ((ap_const_logic_1 == ap_reg_ready_kernel_val_1_0_channel_full_n)) begin
        ap_chn_write_conv_Loop_1_proc_U0_kernel_val_1_0_channel = ap_const_logic_0;
    end else begin
        ap_chn_write_conv_Loop_1_proc_U0_kernel_val_1_0_channel = conv_Loop_1_proc_U0_ap_done;
    end
end

always @ (conv_Loop_1_proc_U0_ap_done or ap_reg_ready_kernel_val_1_1_channel_full_n) begin
    if ((ap_const_logic_1 == ap_reg_ready_kernel_val_1_1_channel_full_n)) begin
        ap_chn_write_conv_Loop_1_proc_U0_kernel_val_1_1_channel = ap_const_logic_0;
    end else begin
        ap_chn_write_conv_Loop_1_proc_U0_kernel_val_1_1_channel = conv_Loop_1_proc_U0_ap_done;
    end
end

always @ (conv_Loop_1_proc_U0_ap_done or ap_reg_ready_kernel_val_1_2_channel_full_n) begin
    if ((ap_const_logic_1 == ap_reg_ready_kernel_val_1_2_channel_full_n)) begin
        ap_chn_write_conv_Loop_1_proc_U0_kernel_val_1_2_channel = ap_const_logic_0;
    end else begin
        ap_chn_write_conv_Loop_1_proc_U0_kernel_val_1_2_channel = conv_Loop_1_proc_U0_ap_done;
    end
end

always @ (conv_Loop_1_proc_U0_ap_done or ap_reg_ready_kernel_val_2_0_channel_full_n) begin
    if ((ap_const_logic_1 == ap_reg_ready_kernel_val_2_0_channel_full_n)) begin
        ap_chn_write_conv_Loop_1_proc_U0_kernel_val_2_0_channel = ap_const_logic_0;
    end else begin
        ap_chn_write_conv_Loop_1_proc_U0_kernel_val_2_0_channel = conv_Loop_1_proc_U0_ap_done;
    end
end

always @ (conv_Loop_1_proc_U0_ap_done or ap_reg_ready_kernel_val_2_1_channel_full_n) begin
    if ((ap_const_logic_1 == ap_reg_ready_kernel_val_2_1_channel_full_n)) begin
        ap_chn_write_conv_Loop_1_proc_U0_kernel_val_2_1_channel = ap_const_logic_0;
    end else begin
        ap_chn_write_conv_Loop_1_proc_U0_kernel_val_2_1_channel = conv_Loop_1_proc_U0_ap_done;
    end
end

always @ (conv_Loop_1_proc_U0_ap_done or ap_reg_ready_kernel_val_2_2_channel_full_n) begin
    if ((ap_const_logic_1 == ap_reg_ready_kernel_val_2_2_channel_full_n)) begin
        ap_chn_write_conv_Loop_1_proc_U0_kernel_val_2_2_channel = ap_const_logic_0;
    end else begin
        ap_chn_write_conv_Loop_1_proc_U0_kernel_val_2_2_channel = conv_Loop_1_proc_U0_ap_done;
    end
end

always @ (conv_Block_proc9_U0_ap_idle or conv_AXIM2Mat_U0_ap_idle or conv_Loop_1_proc_U0_ap_idle or conv_Filter2D_U0_ap_idle or conv_Mat2AXIM_U0_ap_idle or kernel_val_0_0_channel_empty_n or kernel_val_0_1_channel_empty_n or kernel_val_0_2_channel_empty_n or kernel_val_1_0_channel_empty_n or kernel_val_1_1_channel_empty_n or kernel_val_1_2_channel_empty_n or kernel_val_2_0_channel_empty_n or kernel_val_2_1_channel_empty_n or kernel_val_2_2_channel_empty_n) begin
    if (((ap_const_logic_1 == conv_Block_proc9_U0_ap_idle) & (ap_const_logic_1 == conv_AXIM2Mat_U0_ap_idle) & (ap_const_logic_1 == conv_Loop_1_proc_U0_ap_idle) & (ap_const_logic_1 == conv_Filter2D_U0_ap_idle) & (ap_const_logic_1 == conv_Mat2AXIM_U0_ap_idle) & (ap_const_logic_0 == kernel_val_0_0_channel_empty_n) & (ap_const_logic_0 == kernel_val_0_1_channel_empty_n) & (ap_const_logic_0 == kernel_val_0_2_channel_empty_n) & (ap_const_logic_0 == kernel_val_1_0_channel_empty_n) & (ap_const_logic_0 == kernel_val_1_1_channel_empty_n) & (ap_const_logic_0 == kernel_val_1_2_channel_empty_n) & (ap_const_logic_0 == kernel_val_2_0_channel_empty_n) & (ap_const_logic_0 == kernel_val_2_1_channel_empty_n) & (ap_const_logic_0 == kernel_val_2_2_channel_empty_n))) begin
        ap_idle = ap_const_logic_1;
    end else begin
        ap_idle = ap_const_logic_0;
    end
end

always @ (conv_Mat2AXIM_U0_ap_done) begin
    if ((ap_const_logic_1 == conv_Mat2AXIM_U0_ap_done)) begin
        ap_sig_hs_done = ap_const_logic_1;
    end else begin
        ap_sig_hs_done = ap_const_logic_0;
    end
end

always @ (conv_AXIM2Mat_U0_ap_ready or ap_reg_ready_conv_AXIM2Mat_U0_ap_ready) begin
    if ((ap_const_logic_0 == ap_reg_ready_conv_AXIM2Mat_U0_ap_ready)) begin
        ap_sig_ready_conv_AXIM2Mat_U0_ap_ready = conv_AXIM2Mat_U0_ap_ready;
    end else begin
        ap_sig_ready_conv_AXIM2Mat_U0_ap_ready = ap_const_logic_1;
    end
end

always @ (conv_Block_proc9_U0_ap_ready or ap_reg_ready_conv_Block_proc9_U0_ap_ready) begin
    if ((ap_const_logic_0 == ap_reg_ready_conv_Block_proc9_U0_ap_ready)) begin
        ap_sig_ready_conv_Block_proc9_U0_ap_ready = conv_Block_proc9_U0_ap_ready;
    end else begin
        ap_sig_ready_conv_Block_proc9_U0_ap_ready = ap_const_logic_1;
    end
end

always @ (kernel_val_0_0_channel_full_n or ap_reg_ready_kernel_val_0_0_channel_full_n) begin
    if ((ap_const_logic_0 == ap_reg_ready_kernel_val_0_0_channel_full_n)) begin
        ap_sig_ready_kernel_val_0_0_channel_full_n = kernel_val_0_0_channel_full_n;
    end else begin
        ap_sig_ready_kernel_val_0_0_channel_full_n = ap_const_logic_1;
    end
end

always @ (kernel_val_0_1_channel_full_n or ap_reg_ready_kernel_val_0_1_channel_full_n) begin
    if ((ap_const_logic_0 == ap_reg_ready_kernel_val_0_1_channel_full_n)) begin
        ap_sig_ready_kernel_val_0_1_channel_full_n = kernel_val_0_1_channel_full_n;
    end else begin
        ap_sig_ready_kernel_val_0_1_channel_full_n = ap_const_logic_1;
    end
end

always @ (kernel_val_0_2_channel_full_n or ap_reg_ready_kernel_val_0_2_channel_full_n) begin
    if ((ap_const_logic_0 == ap_reg_ready_kernel_val_0_2_channel_full_n)) begin
        ap_sig_ready_kernel_val_0_2_channel_full_n = kernel_val_0_2_channel_full_n;
    end else begin
        ap_sig_ready_kernel_val_0_2_channel_full_n = ap_const_logic_1;
    end
end

always @ (kernel_val_1_0_channel_full_n or ap_reg_ready_kernel_val_1_0_channel_full_n) begin
    if ((ap_const_logic_0 == ap_reg_ready_kernel_val_1_0_channel_full_n)) begin
        ap_sig_ready_kernel_val_1_0_channel_full_n = kernel_val_1_0_channel_full_n;
    end else begin
        ap_sig_ready_kernel_val_1_0_channel_full_n = ap_const_logic_1;
    end
end

always @ (kernel_val_1_1_channel_full_n or ap_reg_ready_kernel_val_1_1_channel_full_n) begin
    if ((ap_const_logic_0 == ap_reg_ready_kernel_val_1_1_channel_full_n)) begin
        ap_sig_ready_kernel_val_1_1_channel_full_n = kernel_val_1_1_channel_full_n;
    end else begin
        ap_sig_ready_kernel_val_1_1_channel_full_n = ap_const_logic_1;
    end
end

always @ (kernel_val_1_2_channel_full_n or ap_reg_ready_kernel_val_1_2_channel_full_n) begin
    if ((ap_const_logic_0 == ap_reg_ready_kernel_val_1_2_channel_full_n)) begin
        ap_sig_ready_kernel_val_1_2_channel_full_n = kernel_val_1_2_channel_full_n;
    end else begin
        ap_sig_ready_kernel_val_1_2_channel_full_n = ap_const_logic_1;
    end
end

always @ (kernel_val_2_0_channel_full_n or ap_reg_ready_kernel_val_2_0_channel_full_n) begin
    if ((ap_const_logic_0 == ap_reg_ready_kernel_val_2_0_channel_full_n)) begin
        ap_sig_ready_kernel_val_2_0_channel_full_n = kernel_val_2_0_channel_full_n;
    end else begin
        ap_sig_ready_kernel_val_2_0_channel_full_n = ap_const_logic_1;
    end
end

always @ (kernel_val_2_1_channel_full_n or ap_reg_ready_kernel_val_2_1_channel_full_n) begin
    if ((ap_const_logic_0 == ap_reg_ready_kernel_val_2_1_channel_full_n)) begin
        ap_sig_ready_kernel_val_2_1_channel_full_n = kernel_val_2_1_channel_full_n;
    end else begin
        ap_sig_ready_kernel_val_2_1_channel_full_n = ap_const_logic_1;
    end
end

always @ (kernel_val_2_2_channel_full_n or ap_reg_ready_kernel_val_2_2_channel_full_n) begin
    if ((ap_const_logic_0 == ap_reg_ready_kernel_val_2_2_channel_full_n)) begin
        ap_sig_ready_kernel_val_2_2_channel_full_n = kernel_val_2_2_channel_full_n;
    end else begin
        ap_sig_ready_kernel_val_2_2_channel_full_n = ap_const_logic_1;
    end
end

always @ (ap_start or ap_reg_ready_conv_AXIM2Mat_U0_ap_ready) begin
    if (((ap_const_logic_1 == ap_start) & (ap_const_logic_0 == ap_reg_ready_conv_AXIM2Mat_U0_ap_ready))) begin
        ap_sig_start_in_conv_AXIM2Mat_U0_ap_start = ap_const_logic_1;
    end else begin
        ap_sig_start_in_conv_AXIM2Mat_U0_ap_start = ap_const_logic_0;
    end
end

always @ (ap_start or ap_reg_ready_conv_Block_proc9_U0_ap_ready) begin
    if (((ap_const_logic_0 == ap_reg_ready_conv_Block_proc9_U0_ap_ready) & (ap_const_logic_1 == ap_start))) begin
        ap_sig_start_in_conv_Block_proc9_U0_ap_start = ap_const_logic_1;
    end else begin
        ap_sig_start_in_conv_Block_proc9_U0_ap_start = ap_const_logic_0;
    end
end

always @ (ap_sig_ready_conv_Block_proc9_U0_ap_ready or ap_sig_ready_conv_AXIM2Mat_U0_ap_ready) begin
    if (((ap_const_logic_1 == ap_sig_ready_conv_Block_proc9_U0_ap_ready) & (ap_const_logic_1 == ap_sig_ready_conv_AXIM2Mat_U0_ap_ready))) begin
        ap_sig_top_allready = ap_const_logic_1;
    end else begin
        ap_sig_top_allready = ap_const_logic_0;
    end
end

always @ (ap_sig_ready_kernel_val_0_0_channel_full_n or ap_sig_ready_kernel_val_0_1_channel_full_n or ap_sig_ready_kernel_val_1_0_channel_full_n or ap_sig_ready_kernel_val_2_0_channel_full_n or ap_sig_ready_kernel_val_1_1_channel_full_n or ap_sig_ready_kernel_val_1_2_channel_full_n or ap_sig_ready_kernel_val_0_2_channel_full_n or ap_sig_ready_kernel_val_2_2_channel_full_n or ap_sig_ready_kernel_val_2_1_channel_full_n) begin
    if (((ap_const_logic_1 == ap_sig_ready_kernel_val_0_0_channel_full_n) & (ap_const_logic_1 == ap_sig_ready_kernel_val_0_1_channel_full_n) & (ap_const_logic_1 == ap_sig_ready_kernel_val_1_0_channel_full_n) & (ap_const_logic_1 == ap_sig_ready_kernel_val_2_0_channel_full_n) & (ap_const_logic_1 == ap_sig_ready_kernel_val_1_1_channel_full_n) & (ap_const_logic_1 == ap_sig_ready_kernel_val_1_2_channel_full_n) & (ap_const_logic_1 == ap_sig_ready_kernel_val_0_2_channel_full_n) & (ap_const_logic_1 == ap_sig_ready_kernel_val_2_2_channel_full_n) & (ap_const_logic_1 == ap_sig_ready_kernel_val_2_1_channel_full_n))) begin
        conv_Loop_1_proc_U0_ap_continue = ap_const_logic_1;
    end else begin
        conv_Loop_1_proc_U0_ap_continue = ap_const_logic_0;
    end
end

assign CRTL_BUS_ARADDR = conv_AXIM2Mat_U0_m_axi_fb_ARADDR;

assign CRTL_BUS_ARBURST = conv_AXIM2Mat_U0_m_axi_fb_ARBURST;

assign CRTL_BUS_ARCACHE = conv_AXIM2Mat_U0_m_axi_fb_ARCACHE;

assign CRTL_BUS_ARID = conv_AXIM2Mat_U0_m_axi_fb_ARID;

assign CRTL_BUS_ARLEN = conv_AXIM2Mat_U0_m_axi_fb_ARLEN;

assign CRTL_BUS_ARLOCK = conv_AXIM2Mat_U0_m_axi_fb_ARLOCK;

assign CRTL_BUS_ARPROT = conv_AXIM2Mat_U0_m_axi_fb_ARPROT;

assign CRTL_BUS_ARQOS = conv_AXIM2Mat_U0_m_axi_fb_ARQOS;

assign CRTL_BUS_ARREGION = conv_AXIM2Mat_U0_m_axi_fb_ARREGION;

assign CRTL_BUS_ARSIZE = conv_AXIM2Mat_U0_m_axi_fb_ARSIZE;

assign CRTL_BUS_ARUSER = conv_AXIM2Mat_U0_m_axi_fb_ARUSER;

assign CRTL_BUS_ARVALID = conv_AXIM2Mat_U0_m_axi_fb_ARVALID;

assign CRTL_BUS_AWADDR = conv_Mat2AXIM_U0_m_axi_fb_AWADDR;

assign CRTL_BUS_AWBURST = conv_Mat2AXIM_U0_m_axi_fb_AWBURST;

assign CRTL_BUS_AWCACHE = conv_Mat2AXIM_U0_m_axi_fb_AWCACHE;

assign CRTL_BUS_AWID = conv_Mat2AXIM_U0_m_axi_fb_AWID;

assign CRTL_BUS_AWLEN = conv_Mat2AXIM_U0_m_axi_fb_AWLEN;

assign CRTL_BUS_AWLOCK = conv_Mat2AXIM_U0_m_axi_fb_AWLOCK;

assign CRTL_BUS_AWPROT = conv_Mat2AXIM_U0_m_axi_fb_AWPROT;

assign CRTL_BUS_AWQOS = conv_Mat2AXIM_U0_m_axi_fb_AWQOS;

assign CRTL_BUS_AWREGION = conv_Mat2AXIM_U0_m_axi_fb_AWREGION;

assign CRTL_BUS_AWSIZE = conv_Mat2AXIM_U0_m_axi_fb_AWSIZE;

assign CRTL_BUS_AWUSER = conv_Mat2AXIM_U0_m_axi_fb_AWUSER;

assign CRTL_BUS_AWVALID = conv_Mat2AXIM_U0_m_axi_fb_AWVALID;

assign CRTL_BUS_BREADY = conv_Mat2AXIM_U0_m_axi_fb_BREADY;

assign CRTL_BUS_RREADY = conv_AXIM2Mat_U0_m_axi_fb_RREADY;

assign CRTL_BUS_WDATA = conv_Mat2AXIM_U0_m_axi_fb_WDATA;

assign CRTL_BUS_WID = conv_Mat2AXIM_U0_m_axi_fb_WID;

assign CRTL_BUS_WLAST = conv_Mat2AXIM_U0_m_axi_fb_WLAST;

assign CRTL_BUS_WSTRB = conv_Mat2AXIM_U0_m_axi_fb_WSTRB;

assign CRTL_BUS_WUSER = conv_Mat2AXIM_U0_m_axi_fb_WUSER;

assign CRTL_BUS_WVALID = conv_Mat2AXIM_U0_m_axi_fb_WVALID;

assign ap_done = ap_sig_hs_done;

assign ap_ready = ap_sig_top_allready;


always @ (ap_rst_n) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign ap_sig_hs_continue = ap_const_logic_1;

assign conv_AXILiteS_s_axi_U_ap_dummy_ce = ap_const_logic_1;

assign conv_AXIM2Mat_U0_ap_continue = ap_const_logic_1;

assign conv_AXIM2Mat_U0_ap_start = ap_sig_start_in_conv_AXIM2Mat_U0_ap_start;

assign conv_AXIM2Mat_U0_image_in_dout = image_in_channel_dout;

assign conv_AXIM2Mat_U0_image_in_empty_n = image_in_channel_empty_n;

assign conv_AXIM2Mat_U0_img_cols_V_dout = src_cols_V_channel_dout;

assign conv_AXIM2Mat_U0_img_cols_V_empty_n = src_cols_V_channel_empty_n;

assign conv_AXIM2Mat_U0_img_data_stream_V_full_n = src_data_stream_0_V_full_n;

assign conv_AXIM2Mat_U0_img_rows_V_dout = src_rows_V_channel_dout;

assign conv_AXIM2Mat_U0_img_rows_V_empty_n = src_rows_V_channel_empty_n;

assign conv_AXIM2Mat_U0_m_axi_fb_ARREADY = CRTL_BUS_ARREADY;

assign conv_AXIM2Mat_U0_m_axi_fb_AWREADY = ap_const_logic_0;

assign conv_AXIM2Mat_U0_m_axi_fb_BID = ap_const_lv1_0;

assign conv_AXIM2Mat_U0_m_axi_fb_BRESP = ap_const_lv2_0;

assign conv_AXIM2Mat_U0_m_axi_fb_BUSER = ap_const_lv1_0;

assign conv_AXIM2Mat_U0_m_axi_fb_BVALID = ap_const_logic_0;

assign conv_AXIM2Mat_U0_m_axi_fb_RDATA = CRTL_BUS_RDATA;

assign conv_AXIM2Mat_U0_m_axi_fb_RID = CRTL_BUS_RID;

assign conv_AXIM2Mat_U0_m_axi_fb_RLAST = CRTL_BUS_RLAST;

assign conv_AXIM2Mat_U0_m_axi_fb_RRESP = CRTL_BUS_RRESP;

assign conv_AXIM2Mat_U0_m_axi_fb_RUSER = CRTL_BUS_RUSER;

assign conv_AXIM2Mat_U0_m_axi_fb_RVALID = CRTL_BUS_RVALID;

assign conv_AXIM2Mat_U0_m_axi_fb_WREADY = ap_const_logic_0;

assign conv_Block_proc9_U0_ap_continue = ap_const_logic_1;

assign conv_Block_proc9_U0_ap_start = ap_sig_start_in_conv_Block_proc9_U0_ap_start;

assign conv_Block_proc9_U0_image_in = image_in;

assign conv_Block_proc9_U0_image_in_out_full_n = image_in_channel_full_n;

assign conv_Block_proc9_U0_image_out = image_out;

assign conv_Block_proc9_U0_image_out_out_full_n = image_out_channel_full_n;

assign conv_Block_proc9_U0_src_cols_V_out2_full_n = src_cols_V_channel39_full_n;

assign conv_Block_proc9_U0_src_cols_V_out_full_n = src_cols_V_channel_full_n;

assign conv_Block_proc9_U0_src_rows_V_out1_full_n = src_rows_V_channel38_full_n;

assign conv_Block_proc9_U0_src_rows_V_out_full_n = src_rows_V_channel_full_n;

assign conv_CRTL_BUS_m_axi_U_ap_dummy_ce = ap_const_logic_1;

assign conv_Filter2D_U0_ap_continue = ap_const_logic_1;

assign conv_Filter2D_U0_ap_start = (kernel_val_0_0_channel_empty_n & kernel_val_0_1_channel_empty_n & kernel_val_0_2_channel_empty_n & kernel_val_1_0_channel_empty_n & kernel_val_1_1_channel_empty_n & kernel_val_1_2_channel_empty_n & kernel_val_2_0_channel_empty_n & kernel_val_2_1_channel_empty_n & kernel_val_2_2_channel_empty_n);

assign conv_Filter2D_U0_p_dst_data_stream_V_full_n = dst_data_stream_0_V_full_n;

assign conv_Filter2D_U0_p_kernel_val_0_0_read = kernel_val_0_0_channel_dout;

assign conv_Filter2D_U0_p_kernel_val_0_1_read = kernel_val_0_1_channel_dout;

assign conv_Filter2D_U0_p_kernel_val_0_2_read = kernel_val_0_2_channel_dout;

assign conv_Filter2D_U0_p_kernel_val_1_0_read = kernel_val_1_0_channel_dout;

assign conv_Filter2D_U0_p_kernel_val_1_1_read = kernel_val_1_1_channel_dout;

assign conv_Filter2D_U0_p_kernel_val_1_2_read = kernel_val_1_2_channel_dout;

assign conv_Filter2D_U0_p_kernel_val_2_0_read = kernel_val_2_0_channel_dout;

assign conv_Filter2D_U0_p_kernel_val_2_1_read = kernel_val_2_1_channel_dout;

assign conv_Filter2D_U0_p_kernel_val_2_2_read = kernel_val_2_2_channel_dout;

assign conv_Filter2D_U0_p_src_cols_V_dout = src_cols_V_channel39_dout;

assign conv_Filter2D_U0_p_src_cols_V_empty_n = src_cols_V_channel39_empty_n;

assign conv_Filter2D_U0_p_src_data_stream_V_dout = src_data_stream_0_V_dout;

assign conv_Filter2D_U0_p_src_data_stream_V_empty_n = src_data_stream_0_V_empty_n;

assign conv_Filter2D_U0_p_src_rows_V_dout = src_rows_V_channel38_dout;

assign conv_Filter2D_U0_p_src_rows_V_empty_n = src_rows_V_channel38_empty_n;

assign conv_Loop_1_proc_U0_ap_start = ap_start;

assign conv_Mat2AXIM_U0_ap_continue = ap_sig_hs_continue;

assign conv_Mat2AXIM_U0_image_out_dout = image_out_channel_dout;

assign conv_Mat2AXIM_U0_image_out_empty_n = image_out_channel_empty_n;

assign conv_Mat2AXIM_U0_img_data_stream_V_dout = dst_data_stream_0_V_dout;

assign conv_Mat2AXIM_U0_img_data_stream_V_empty_n = dst_data_stream_0_V_empty_n;

assign conv_Mat2AXIM_U0_m_axi_fb_ARREADY = ap_const_logic_0;

assign conv_Mat2AXIM_U0_m_axi_fb_AWREADY = CRTL_BUS_AWREADY;

assign conv_Mat2AXIM_U0_m_axi_fb_BID = CRTL_BUS_BID;

assign conv_Mat2AXIM_U0_m_axi_fb_BRESP = CRTL_BUS_BRESP;

assign conv_Mat2AXIM_U0_m_axi_fb_BUSER = CRTL_BUS_BUSER;

assign conv_Mat2AXIM_U0_m_axi_fb_BVALID = CRTL_BUS_BVALID;

assign conv_Mat2AXIM_U0_m_axi_fb_RDATA = ap_const_lv8_0;

assign conv_Mat2AXIM_U0_m_axi_fb_RID = ap_const_lv1_0;

assign conv_Mat2AXIM_U0_m_axi_fb_RLAST = ap_const_logic_0;

assign conv_Mat2AXIM_U0_m_axi_fb_RRESP = ap_const_lv2_0;

assign conv_Mat2AXIM_U0_m_axi_fb_RUSER = ap_const_lv1_0;

assign conv_Mat2AXIM_U0_m_axi_fb_RVALID = ap_const_logic_0;

assign conv_Mat2AXIM_U0_m_axi_fb_WREADY = CRTL_BUS_WREADY;

assign dst_data_stream_0_V_U_ap_dummy_ce = ap_const_logic_1;

assign dst_data_stream_0_V_din = conv_Filter2D_U0_p_dst_data_stream_V_din;

assign dst_data_stream_0_V_read = conv_Mat2AXIM_U0_img_data_stream_V_read;

assign dst_data_stream_0_V_write = conv_Filter2D_U0_p_dst_data_stream_V_write;

assign image_in_channel_U_ap_dummy_ce = ap_const_logic_1;

assign image_in_channel_din = conv_Block_proc9_U0_image_in_out_din;

assign image_in_channel_read = conv_AXIM2Mat_U0_image_in_read;

assign image_in_channel_write = conv_Block_proc9_U0_image_in_out_write;

assign image_out_channel_U_ap_dummy_ce = ap_const_logic_1;

assign image_out_channel_din = conv_Block_proc9_U0_image_out_out_din;

assign image_out_channel_read = conv_Mat2AXIM_U0_image_out_read;

assign image_out_channel_write = conv_Block_proc9_U0_image_out_out_write;

assign kernel_val_0_0_channel_U_ap_dummy_ce = ap_const_logic_1;

assign kernel_val_0_0_channel_din = conv_Loop_1_proc_U0_ap_return_0;

assign kernel_val_0_0_channel_read = conv_Filter2D_U0_ap_ready;

assign kernel_val_0_0_channel_write = ap_chn_write_conv_Loop_1_proc_U0_kernel_val_0_0_channel;

assign kernel_val_0_1_channel_U_ap_dummy_ce = ap_const_logic_1;

assign kernel_val_0_1_channel_din = conv_Loop_1_proc_U0_ap_return_1;

assign kernel_val_0_1_channel_read = conv_Filter2D_U0_ap_ready;

assign kernel_val_0_1_channel_write = ap_chn_write_conv_Loop_1_proc_U0_kernel_val_0_1_channel;

assign kernel_val_0_2_channel_U_ap_dummy_ce = ap_const_logic_1;

assign kernel_val_0_2_channel_din = conv_Loop_1_proc_U0_ap_return_2;

assign kernel_val_0_2_channel_read = conv_Filter2D_U0_ap_ready;

assign kernel_val_0_2_channel_write = ap_chn_write_conv_Loop_1_proc_U0_kernel_val_0_2_channel;

assign kernel_val_1_0_channel_U_ap_dummy_ce = ap_const_logic_1;

assign kernel_val_1_0_channel_din = conv_Loop_1_proc_U0_ap_return_3;

assign kernel_val_1_0_channel_read = conv_Filter2D_U0_ap_ready;

assign kernel_val_1_0_channel_write = ap_chn_write_conv_Loop_1_proc_U0_kernel_val_1_0_channel;

assign kernel_val_1_1_channel_U_ap_dummy_ce = ap_const_logic_1;

assign kernel_val_1_1_channel_din = conv_Loop_1_proc_U0_ap_return_4;

assign kernel_val_1_1_channel_read = conv_Filter2D_U0_ap_ready;

assign kernel_val_1_1_channel_write = ap_chn_write_conv_Loop_1_proc_U0_kernel_val_1_1_channel;

assign kernel_val_1_2_channel_U_ap_dummy_ce = ap_const_logic_1;

assign kernel_val_1_2_channel_din = conv_Loop_1_proc_U0_ap_return_5;

assign kernel_val_1_2_channel_read = conv_Filter2D_U0_ap_ready;

assign kernel_val_1_2_channel_write = ap_chn_write_conv_Loop_1_proc_U0_kernel_val_1_2_channel;

assign kernel_val_2_0_channel_U_ap_dummy_ce = ap_const_logic_1;

assign kernel_val_2_0_channel_din = conv_Loop_1_proc_U0_ap_return_6;

assign kernel_val_2_0_channel_read = conv_Filter2D_U0_ap_ready;

assign kernel_val_2_0_channel_write = ap_chn_write_conv_Loop_1_proc_U0_kernel_val_2_0_channel;

assign kernel_val_2_1_channel_U_ap_dummy_ce = ap_const_logic_1;

assign kernel_val_2_1_channel_din = conv_Loop_1_proc_U0_ap_return_7;

assign kernel_val_2_1_channel_read = conv_Filter2D_U0_ap_ready;

assign kernel_val_2_1_channel_write = ap_chn_write_conv_Loop_1_proc_U0_kernel_val_2_1_channel;

assign kernel_val_2_2_channel_U_ap_dummy_ce = ap_const_logic_1;

assign kernel_val_2_2_channel_din = conv_Loop_1_proc_U0_ap_return_8;

assign kernel_val_2_2_channel_read = conv_Filter2D_U0_ap_ready;

assign kernel_val_2_2_channel_write = ap_chn_write_conv_Loop_1_proc_U0_kernel_val_2_2_channel;

assign src_cols_V_channel39_U_ap_dummy_ce = ap_const_logic_1;

assign src_cols_V_channel39_din = conv_Block_proc9_U0_src_cols_V_out2_din;

assign src_cols_V_channel39_read = conv_Filter2D_U0_p_src_cols_V_read;

assign src_cols_V_channel39_write = conv_Block_proc9_U0_src_cols_V_out2_write;

assign src_cols_V_channel_U_ap_dummy_ce = ap_const_logic_1;

assign src_cols_V_channel_din = conv_Block_proc9_U0_src_cols_V_out_din;

assign src_cols_V_channel_read = conv_AXIM2Mat_U0_img_cols_V_read;

assign src_cols_V_channel_write = conv_Block_proc9_U0_src_cols_V_out_write;

assign src_data_stream_0_V_U_ap_dummy_ce = ap_const_logic_1;

assign src_data_stream_0_V_din = conv_AXIM2Mat_U0_img_data_stream_V_din;

assign src_data_stream_0_V_read = conv_Filter2D_U0_p_src_data_stream_V_read;

assign src_data_stream_0_V_write = conv_AXIM2Mat_U0_img_data_stream_V_write;

assign src_rows_V_channel38_U_ap_dummy_ce = ap_const_logic_1;

assign src_rows_V_channel38_din = conv_Block_proc9_U0_src_rows_V_out1_din;

assign src_rows_V_channel38_read = conv_Filter2D_U0_p_src_rows_V_read;

assign src_rows_V_channel38_write = conv_Block_proc9_U0_src_rows_V_out1_write;

assign src_rows_V_channel_U_ap_dummy_ce = ap_const_logic_1;

assign src_rows_V_channel_din = conv_Block_proc9_U0_src_rows_V_out_din;

assign src_rows_V_channel_read = conv_AXIM2Mat_U0_img_rows_V_read;

assign src_rows_V_channel_write = conv_Block_proc9_U0_src_rows_V_out_write;


endmodule //conv

